### ISSUE TITLE
[soapservices] Rozšíření vyhledávání o signaturu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/registrdigitalizace#196]
```
SOAP služba by měla být rozšířena o možnost vyhledávání podle 
signatury.
```

Original issue reported on code.google.com by `pokor...@gmail.com` on 3 Sep 2012 at 5:00

**Comment by MKortus** [comment]
issu bylo uzavřeno již v předchozí aplikaci GoogleCode. proto uzavírám
