### ISSUE TITLE
zahrnutí digitalizace VISK7 do DK NK ČR

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/registrdigitalizace#280]
```
Prosím započítat a zařadit do vyhledávání pod "Digitální knihovna NK 
ČR" (ABA001-DK v agendě digitálních knihoven) též všechny záznamy 
jiných sigel než ABA001 a ABA004, které  mají v poli Financováno "VISK7" - 
bez ohledu na to, zda je či není vyplněno pole digknihovna (tj. pokud mají 
vlastní DK, mají se zařadit a vyhledat/filtrovat pod oběma DK). 

Bylo dohodnuto a odsouhlaseno na schůzce vývojového týmu.
```

Original issue reported on code.google.com by `helena....@gmail.com` on 28 Feb 2013 at 10:37

**Comment by helena-oks** [comment]
Předpokládané řešení pro nový web:

Do dig.knihovny budou vždy zařazeny všechny záznamy, které obsahují "prefix" určité dig.knihovny v polích URL, URLTITUL, URLTITNK nebo budou mít připojené UUID sklizené z příslušných krameriů.  (Digitalizace VISK7 obsahuje URL do krameria NK - starého - v poli URLTITNK).

Zruší se tedy i vazba Přispěvatel - Digitální knihovna. 

Po realizaci bude možno uzavřít.

**Comment by helena-oks** [comment]
Vyřešeno v novém webu, možno uzavřít.
