### ISSUE TITLE
Harvest K4 NDK do RDCZ

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/registrdigitalizace#322]
```
po instalaci produkčního Oracle
```

Original issue reported on code.google.com by `pavel.ko...@incad.cz` on 23 Jul 2013 at 7:35

**Comment by helena-oks** [comment]
Kdy budou do RD doplněny URL z digitalizace NDK? Neurgovala jsem požadavek v očekávání, že se to vyřeší v rámci spolupráce nad NDK, jedná se totiž o přidání linků nejen k záznamům NK, ale i MZK.

Aby nedošlo k nějakým nedopatřením, protože jde o velkou masu záznamů, zde upozorňuju, na co je třeba dát pozor, i když s tím nejspíš počítáte:

1/ URL je třeba přidat, když souhlasí sigla a identifikátor (pole 001) a čárový kód v metadatech digitalizovaného dokumentu a v RD (do pole URL)
2/ Protože v krameriovi NK i krameriovi MZK by měly být stejné dokumenty (stejné uuid, v URL se liší jen první část, jméno serveru), je třeba zajistit, aby si vždy odpovídala sigla a jméno serveru (ABA001 = kramerius4.nkp.cz, BOA001 = kramerius.mzk.cz)
3/ v případě seriálů musí být do pole URLTITUL umístěna nejvyšší úroveň URL (buď navíc, nebo místo pole URL odpovídajcícho jednotlivým ročníkům)
4/ protože RD umí uložit pouze jedno URL, mohou vzniknout problémy s přívazky a jinými nestandardními situacemi: je nutné, aby akce neproběhla, pokud se neshodne jeden z porovnávaných údajů, a aby se  "neúspěšné pokusy o přiřazení" ukládaly do nějakého výstupu
(pak budeme analyzovat a řešit, co s tím)

**Comment by helena-oks** [comment]
Než se akce zahájí, chci být informována. Dále prosím o statistiku (sigla + počty úspěch/neúspěch) + výpisy "neúspěchů".

Předpokládám, že doplňování URL bude po "velkém třesku" stejným způsobem probíhat automaticky - na základě periodických sklizní nových/aktualizovaných záznamů z krameriů. Interval sklizní by neměl být delší než měsíc, jako optimální vidím týdenní periodicitu.

**Comment by helena-oks** [comment]
Prosím o odpověď, zda se v této věci něco dělá.

Dále doufám, že se počítá s ukládáním persistentního URL, nikoli vyhledávacího řetězce, což musím připomínat i jiným knihovnám.
(tedy ...handle/uuid..., a nikoli ...i.jsp?pid=uuid...)

**Comment by helena-oks** [comment]
Kdy budou konečně doplněny URL z K4? Zpráva od pana Kocourka panu Foltýnovi z 14.4.  slibovala doplnění v řádu jednotek týdnů.  Bylo též připomínáno na květnové schůzce k duplicitám.

**Comment by pavelkocourek** [comment]
Dobrý den, 
v minulém týdnu jsme pro Krameria publikovali nový OAI provider https://github.com/ceskaexpedice/kramerius/blob/bf51685204943c596d525a075db89f7edbd97b57/installation/oai/README.md 
který dokáže pracovat s objemem dat, který je v NDK. Je založený na vyhledávači SOLR.

Stávající harvestr - defaultní implementace OAI-PMH úložiště Fedora (Komponenta je externím prvkem od třetí strany připojeným k úložišti Krameria) - byl bohužel nefunkční při překročení několika set milionů vazeb v resource indexu. (Vazby mezi objekty ve Fedoře.

V NK je evidován Incident #4106, který měl dopad, krom jiných funkcí i na tento harvest – komunikuju s panem Jaklem. Až bude nasazen správcem v NK, obnovíme harvesty do Registru.

PK

**Comment by helena-oks** [comment]
V dubnu 2017 proběhla celková sklizeň NDK NK a pokus o propojení monografií s předlohami - do značné míry úspěšný.  Zobrazení těchto odkazů se odkládá až na nový uživatelský web. 

Zůstává problém periodik a nepřipojených či špatně připojených UUID monografií. Zakládám proto nové ISSUE a toto bych uzavřela.

**Comment by helena-oks** [comment]
Je možné issue uzavřít.
