### ISSUE TITLE
Změna informací o titulu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/registrdigitalizace#328]
```
Po vytvoření nového záznamu kopií ze stávajícího záznamu a jeho 
následné úpravě má tento nový záznam stejné xml jako původní záznam. 
Neprojeví se v něm ručně provedené změny.





```

Original issue reported on code.google.com by `nezbed...@knav.cz` on 31 Jul 2013 at 8:39

**Comment by MKortus** [comment]
Předpokládám, že XML nese zdrojová data, a pokud je to tak, tak by nemělo docházet k jeho editaci.
Je otázka, jestli v případě vytvoření záznamu kopií, by se místo zkopírování XML nemělo toto pole vymazat a nechat prázdné.

**Comment by nezbedova** [comment]
Vyřešeno změnou v postupu práce.

**Comment by MKortus** [comment]
OK. v tom případě uzavírám. Děkuji
