### ISSUE TITLE
doplnění XLM k ručně založeným záznamům

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/registrdigitalizace#329]
```
Prosím o jednorázové doplnění XML dat do RD ke stávajícím záznamům 
KNAV.

```

Original issue reported on code.google.com by `nezbed...@knav.cz` on 31 Jul 2013 at 9:20

**Comment by MKortus** [comment]
nebylo urgováno, takže vzhledem ke stáří požadavku předpokládám, že je již vyřešeno.

**Comment by nezbedova** [comment]
Jednalo se o jednorázové doplnění (buď čČNB nebo pole 001). Takže to je hotové.

**Comment by MKortus** [comment]
Perfekt. uzavírám. Děkuji
