### ISSUE TITLE
Zásadní nedostatky v uživatelském vyhledávání

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/registrdigitalizace#351]
```
Zjistila jsem dvě základní chyby vyhledávání:

1/ nevyhledává v neplatných ččnb - ani ze základního okénka, ani z 
pokročilého vyhledávání (příklad: cnb000366021)

2/ dává nesprávné odpovědi, pokud je zadáno více slov z názvu a v 
žádném záznamu tato slova nejsou pohromadě - viz příloha

Protože bude po změně nastavení třeba přeindexovat, bylo by dobré to 
spojit 

3/ s úpravou celkového nastavení vyhledávání a relevance, které rovněž 
není vyhovující - viz druhá příloha, souvisí s ISSUE 327. K materiálu 
nepřišly od vývojové skupiny žádné připomínky, tj. je v zásadě 
přijatelný. Plánovaná schůzka pak může navrhnout drobné změny, pokud 
by byla nespokojenost.
```

Original issue reported on code.google.com by `helena....@gmail.com` on 12 Nov 2013 at 8:45

Attachments:
- [RD-vyhledávání-chyba při 0.docx](https://storage.googleapis.com/google-code-attachments/registrdigitalizace/issue-351/comment-0/RD-vyhledávání-chyba při 0.docx)
- [RD-vyhledávací algoritmy-issue.docx](https://storage.googleapis.com/google-code-attachments/registrdigitalizace/issue-351/comment-0/RD-vyhledávací algoritmy-issue.docx)

**Comment by Martin-Novacek-csCZ** [comment]
Zrušený parametr při migraci z G.C.:
CasovaNarocnost-004

**Comment by MKortus** [comment]
toto issue mělo být, podle textu, importováno se statusem uzavřeno. Proto uzavírám.
