### ISSUE TITLE
github

### ISSUE THREAD

**Issue by GoogleCodeExporter** [incad/registrdigitalizace#499]
```
Dotaz ing. Žabičky:

Bude se "dokumentace" s issues pro RD přesouvat na github?
```

Original issue reported on code.google.com by `helena....@gmail.com` on 3 Aug 2015 at 11:47

**Comment by Martin-Novacek-csCZ** [comment]
Zrušený parametr při migraci z G.C.:
CasovaNarocnost-027

**Comment by helena-oks** [comment]
Otestována možnost přístupu.

**Comment by Martin-Novacek-csCZ** [comment]
Migrace dokončena.
Pro případné připomínky k novému systému prosím zakládejte samostatná issues.
