### ISSUE TITLE
Nefungující detaily předloh

### ISSUE THREAD

**Issue by Martin-Novacek-csCZ** [incad/registrdigitalizace#501]
Požadavek na kontrolu vzešel od paní Jelínkové z MZK.
Stěžovala si, že po šesté hodině ráno je vyhledávání pomalé a po rozkliknutí nalezených výsledků detail není úplný.

Dnes jsem to testoval.

1.) Vyhledávání
Zadal jsem stejné vyhledávání jako včera paní Jelínková, ale výsledky se mi vrátili podstatně dříve než jí. Zkusil jsem hledat i další věci, ale vždy vrátil výsledek hledání do pár sekund. Paní Jelínková hlásila, že to někdy trvá i více jak 5 minut, než ráno vrátí vyhledávání výsledek.

2.) Zobrazení detailů
Z detailu se zobrazila jen první šást, ta která je v indexu.
Druhá část, která se tahá z databáze se nezobrazila, byla tam hláška "Načítám předlohy..." a ta tam visela bez další reakce. U prvních pokusů se mi nenačetla ani ikonka pro zavření okna detailu, jak je vidět na prvním screenu.
Poprvé se mi podařilo načíst kompletní detail předlohy až v cca 6:25.

![2015-08-14 06_07_54-registr digitalizace](https://cloud.githubusercontent.com/assets/13659504/9267351/0025b18e-424e-11e5-822b-a9e5dd4ca9e6.png)
![2015-08-14 06_09_59-registr digitalizace](https://cloud.githubusercontent.com/assets/13659504/9267355/05c9ed30-424e-11e5-814d-03a0b07d45ef.png)
![2015-08-14 06_10_47-registr digitalizace](https://cloud.githubusercontent.com/assets/13659504/9267356/0818f8d8-424e-11e5-861a-4f8b3bb1b3d8.png)

**Comment by albertoh** [comment]
V logu tomcatu:
Aug 14, 2015 6:13:27 AM cz.registrdigitalizace.soapservices.DigitizationRegistry findRecords
SEVERE: null
cz.registrdigitalizace.soapservices.datasource.DataSourceException: java.sql.SQLRecoverableException: Io exception: Connection timed out

A nasledne Broken pipe z oracle.

Probiha v databazi nejaka udrzba v tech hodinach?

**Comment by Martin-Novacek-csCZ** [comment]
Načel jsem v CRONu jenom tvorbu záloh.
Ale ta se spouští ve 23:01 a podle logu byla ve 23:50 dokončená.

O dalších servisních úkonech nevím.

**Comment by Martin-Novacek-csCZ** [comment]
Dnes byl proveden test.
Ve stejný okamžik 6:02 ybl zadán požadavek do vyhledávání babička a u nalebených výsledků jsem si jeden vybral a chtěl vidět výsledek... pokus skončil nekonečným čekáním, které je popsané výše.

A v ten samý okamžik jsem šel do Relief a prohraboval se daty, zkoušel jsem i update záznamu, načítání dat ve vícero agendách a vše OK, bez chyby, Relief vracel data bez prodlení. Jedná se o data ve stejné databázi, ve stejném schématu.

Žádnou chybu z Oracle mi to nevrátilo.

Je 6:08 a vyhledávání stále nevrací detaily a při tom celou dobu pracuju v Relief.

**Comment by MKortus** [comment]
Problém se pravděpodobně neopakoval, proto issue uzavírám.
