### ISSUE TITLE
doplnění nového financování + související doplnění importního programu

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#503]
1. Prosím doplnit financování "iop-ndku" - přeložit jako " IOP=udržitelnost"

2. Prosím doplnit další podmínky k vyplňování pole financování při importu podle názvu souboru:

a/ je-li sigla ABA001 (na velikosti písmen nezáleží) a suffix ve jménu souboru začíná "dg" - doplnit financování "iop-ndku"
b/ je-li sigla BOA001 (na velikosti písmen nezáleží) a nejde o druh dokumentu RP - doplnit financování "iop-ndku"

(Zpětné doplnění, kde bude třeba, zajistím přes sql dávky).

**Comment by Martin-Novacek-csCZ** [comment]
Nasazena nová verze Importního programu s touto funkcionalitou.
