### ISSUE TITLE
Předloha ve stavu vyřazeno s připojeným záznamem o mikrofilmování

### ISSUE THREAD

**Issue by Martin-Novacek-csCZ** [incad/registrdigitalizace#507]
Záznam předlohy Pr000039598 byl nastaven k vyřazení, ale automatický systém ho nesmazal z důvodu referencí na soufisející záznamy mikrofilmování.

K záznamu je připojen záznam o mikrofilmování a to konkrétně mikrofilm ČAN: 15955

Je třeba rozhodnout co s tímto záznamem, vyví je ve stavu vyřešeno ale systém ho sám nesmaže.

**Comment by MKortus** [comment]
jednorázový problém, kdy záznam byl vymazán a problém se od 10.2015 neopakoval. Pravděpdodobně lze bez problému uzavřít.
Pokud by se problém opakoval, bude nutné upravit definici v Reliefu.
