### ISSUE TITLE
chyba v mapování CBA001 z OAI ?

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#511]
Zjistila jsem, že záznamy CBA001 (prokazatelně české, mající ččnb) dostávají kód speciálního druhu ZL. Je chyba v mapování? Je třeba všude, kde je ččnb i ZL, ZL smazat.

Příklad z posledního importu: Pr000321727

**Comment by Martin-Novacek-csCZ** [comment]
Než to smažu z databáze, chtělo by to opravit příčinu, aby se to nedělalo na 2x.
U importu z CSV je pravidlo:
V případě že je vyplněn sloupec Specdruh jednou z následujících hodnot GL,ZL,ED, tak je nastavena k záznamu v Relief tato hodnota a hodnota ČČNB je nastavena na NULL(prázdná hodnota).

U XML je pravidlo:
Když v poli <controlfield tag="008">950410s1873    xr     e l    001   cze</controlfield>
je na pozici 16-17 xr, tak se nastaví specdruh = ZL, bez dalších úprav ccnb či jiného pole.


Jak by se to tedy mělo změnit?

**Comment by helena-oks** [comment]
Zdravím, tady došlo k nedorozumění: správně by mělo v mapování být, a to nejen pro OAI, ale pro všechny konverze z MARCXML (tam k těmto chybám myslím nedošlo):

Pokud NENÍ v poli 008 na pozici 16-17 (pozice jsou snad v pořádku, ono to někdy čísluje od 0 a někdy od 1) „xr“, pak dát kód „ZL“. Možná to trochu navíc zabezpečit proti chybám tím, že ZL se může dát jen v případě, že není platné ččnb, tj. není 015a.

hedv

**Comment by Martin-Novacek-csCZ** [comment]
Nasadil jsem novou verzi importního programu, která upravuje nastavení speciálního druhu při zpracování XML.
Nyní je speciální druh nastaven, jen když záznam nemá platné ČČNB.

**Comment by helena-oks** [comment]
Chápu to dobře, že ZL jen za podmínky, že tam není „xr“? (Když není ččnb, může to být i GL, ale to se nedá z ničeho v záznamu zjistit, takže se to doplňovat strojově nemůže – jen v případě xls, když se to tam přímo napíše).

Vím, že otravuju – ale nedají se vyhledat xml k záznamům bez ččnb, a pokud je tam splněna podmínka, že v 008 není xr, doplnit tam dodatečně ZL do specdruh?  Jestli je to složité, tak to neřešme.

hedv

**Comment by helena-oks** [comment]
Chyba přetrvává!

Výsledek dotazu:
select count(*) from rlf_nkp_digital.predloha
where specdruh='ZL' and ccnb is not null and zaldate > '10.10.2015';

je dost nedobrý - 1881 záznamů!

Prosím urychleně upravit importní program a smazat specdruh ZL všude, kde je ččnb. ZL a ččnb se vylučují.

**Comment by Martin-Novacek-csCZ** [comment]
Byla nasazena nová verze Importního programu upravující pravidla pro ZL.

Smazání "ZL" se má provést jen u záznamů NK nebo u všech?

**Comment by helena-oks** [comment]
Je-li ččnb, pak nemůže být ZL, tedy u všeho.

**Comment by Martin-Novacek-csCZ** [comment]
Provedena změna v DB:
LOG:
2 135 rows updated.
