### ISSUE TITLE
import ve stavu finished - nepřidáno URL

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#521]
Včerejší dávka  20151207142725_ABA013_h_151207.csv  obsahovala URL na titul, které nebylo importováno. Šlo o přepis záznamů již jednou poslaných ve stavu záměr nebo zpracování, import byl právě kvůli doplnění URL standardní cestou. Protože se stav změnil na dokončeno, takže import znovu neproběhne, prosím doplnit URL sql cestou přes pole 001. A hlavně zjistit, proč se tak stalo!

**Comment by helena-oks** [comment]
Zkusila jsem dnes import znovu, po změně stavu původních záznamů na progress. Soubor ABA013_h_151207a.csv (nepatrně upravený původní). Aktualizace i změna stavu na finished proběhly, ale URL se nedoplnilo - ani do pole URLTITUL, ani do pole URL. Asi k chybě došlo při nějaké modifikaci programu (doplňování pole pro datum URL), protože původně se (myslím) URL doplňovalo řádně.  Ověřit, zda chyba je jen u csv.

**Comment by Martin-Novacek-csCZ** [comment]
Na produkci byla nasazena nová verze importního programu s opravenou chybou, kdy došlo v určitém případě k nedoplnění URL.

Testováno na souboru ABA013_h_151207a.csv.
URL bylo po testu doplněno.
