### ISSUE TITLE
chyba importní větve R1, doplnění záznamu

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#522]
Při importu větví R1 se nesmí  přidávat ani přepisovat URL/URLTITUL! 

Podle zadání má dojít k přidání - v případě, že dosud není - pouze u polí Místo vydání, Vydavatel, Edice. Dále pokud tam není to stejné: Variantní název, neplatná ččnb, neplatná ISSN. Přepisovat se nesmí nic.
Viz tabulka.

Prosím o smazání URLTITUL u záznamů ABA008, kde je dnešní datum aktualizace a kde URLTITUL obsahuje řetězec "nkp".

**Comment by helena-oks** [comment]
Pokud je to komplikované, tak neplatná ččnb i neplatná ISSN, příp. i variantní názvy by se mohly přepsat (v původním záznamu obvykle nejsou nebo jich tam je méně).

**Comment by helena-oks** [comment]
Dávám přednost rychlé náhradě ztraceného původního URLTITUL těmito příkazy místo původní žádosti o smazání chybného URLTITUL:

update rlf_nkp_digital.predloha set urltitul='http://kramerius.medvik.cz/search/handle/uuid:MED00010976-visk' where sigla1='ABA008' and pole001='MED00010976';
update rlf_nkp_digital.predloha set urltitul='http://kramerius.medvik.cz/search/handle/uuid:MED00012155' where sigla1='ABA008' and pole001='MED00012155';
update rlf_nkp_digital.predloha set urltitul='http://kramerius.medvik.cz/search/handle/uuid:MED00012481' where sigla1='ABA008' and pole001='MED00012481';
update rlf_nkp_digital.predloha set urltitul='http://kramerius.medvik.cz/search/handle/uuid:MED00012482' where sigla1='ABA008' and pole001='MED00012482';
update rlf_nkp_digital.predloha set urltitul='http://kramerius.medvik.cz/search/handle/uuid:MED00012655' where sigla1='ABA008' and pole001='MED00012655';

**Comment by Martin-Novacek-csCZ** [comment]
Data byla opravena přes SQL:
41 rows updated.
16 rows updated.
21 rows updated.
10 rows updated.
18 rows updated.

**Comment by Martin-Novacek-csCZ** [comment]
R1 momentálně updatuje více polí, ale updatuje pouze tehdy, pokud existují v příchozích datech.
Takto je možné aktualizovat skoro všechna pole, když je zaslána nová hodnota, tak je v Relief aktualizována, když hodnota není zaslána, tak pole zůstane bezezměny.
Touto metodou tedy nejde nastavit prázdnou hodnotu.

Př:
Pokud přijde záznam v CSV s prázdným názvem (bez názvu), tak u záznamu v Relief nedojde k přepsání původního názvu prázdnou hodnotou a z§stane původní hodnota.

Když ale přijde v CSV záznam s vyplněnou hodnotou názvu, tak je záznam v Relief updatován a je nastaven nový název.


Ale z toho co je napsáno v prvním komentáři by se měly updatovat jen následující pole:
Místo vydání
Vydavatel
Edice

Dále pokud tam není to stejné:
Variantní název
neplatná ččnb
neplatná ISSN

a nic víc, žádná jiná pole tedy pomocí R1 nemají být možné aktualizovat. jen těchto 6?

**Comment by helena-oks** [comment]
Jaký je tedy momentálně rozdíl mezi R0 a R1? Má být dosti zásadní!

Zadání jsem zapsala podrobně do tabulky mapování polí (viz příloha, jestli prošla) a nejspíš i do nějakého issue, které po převodu na github už nenajdu. 
[RD-mapovaci_ tabulka_importni_verze.xlsx](https://github.com/incad/registrdigitalizace/files/60911/RD-mapovaci_.tabulka_importni_verze.xlsx)

R1 má sloužit výhradně k DOPLNĚNÍ důležitých údajů ze záznamu v ČNB do záznamů CIZÍCH knihoven, které si ovšem nepřejí, aby jejich údaje byly přepsány. Proto se např. nesmí přepsat pole 001 (v zaslaném záznamu je úplně jiné), na to jsem zvlášť upozornila při testování R1 (že se přepsal i název jsem nepoznala, protože byl stejný). Tj. jiných než vyjmenovaných polí si R1 nesmí vůbec všímat. 
Oproti tomu R0 má sloužit k přepisu (vybraných údajů), jde o aktualizaci záznamu, u něhož se v katalogu změnily/přidaly/doplnily BIB údaje. R0 je snad v pořádku, bylo už využíváno hodně a na zádrhel jsem nenarazila. 

Takže vyjmenovaná pole nemají být v R1 aktualizována, pouze přidána (pokud tam není to stejné - u těch variant a neplatných údajů bych připustila přepsání, pokud by to porovnávání na stejnost bylo moc složité). Ale nepočítám, že bych posílala na R1 záznamy, které už místo vydání, vydavatele či edici mají... Důležité je taky, aby přibyla neplatná ččnb.

**Comment by Martin-Novacek-csCZ** [comment]
Procházel jsem tu tabulku a možná došlo k nedorozumění.
R1 má editovat pouze pole kde je to výslovně napsáno.
Jedná se tedy o následující pole:

Variantní název
Místo vydání
Vydavatel
ČNB (pouze neplatná)
ISBN/ISMN (pouze platná)
Edice
Č.svazku v edici
Aktualizace XML

U ostatních polí nebyla zmíňka o R1 a zůstanou tedy ignorována.

**Comment by helena-oks** [comment]
Ano, přesně tak!

**Comment by Martin-Novacek-csCZ** [comment]
Když už jsem v tom.
U vybraných polí bude fungovat update následovně.

Pole v Relief bude updatováno pouze v případě, že je prázdné.
Pokud tedy u záznamu v Relief bude vyplněný vydavatel, tak i když v importních datech přijde zázanm s vyplněným vydavatelem, tak původní vydavatel nebude přepsán a zůstane původní hodnota.
Hodnota pole v záznamu Relief bude doplněna pouze tehdy, když v Relief bude prázdná.

**Comment by helena-oks** [comment]
Potvrzuji, že takto to má být. Prosím o brzkou implementaci.

**Comment by Martin-Novacek-csCZ** [comment]
Nasazena nová verze importního programu se změnami pro větev R1.
