### ISSUE TITLE
importní program - špatné přidělování specdruh=ZL (návaznost na issue 511)

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#524]
správně by mělo v mapování být, a to nejen pro OAI, ale pro všechny konverze z MARCXML (tam k těmto chybám myslím nedošlo): Pokud NENÍ v poli 008 na pozici 16-17 (pozice jsou snad v pořádku, ono to někdy čísluje od 0 a někdy od 1) „xr“, pak dát kód „ZL“. Možná to trochu navíc zabezpečit proti chybám tím, že ZL se může dát jen v případě, že není platné ččnb, tj. není 015a.

**Comment by helena-oks** [comment]
Importní program opraven chybně - v mnoha případech (např. poslední import ABE304) byl přidělen kód ZL, i když v poli 008 bylo na příslušné pozici xr.  Dochází k chybnému přiřazení zhruba od počátku prosince - lze zjistit výpisem specdruh=ZL + místo vydání (často i Praha). Vypadá to, že pole008 se nekontroluje a ZL se přiděluje, když není ččnb!

**Comment by helena-oks** [comment]
Zjistila jsem dále, že kód ZL nebyl vymazán u starších záznamů CBA001 a také že byl nesprávně přidělován již začátkem listopadu. 

Prosím vymazat ZL (hned, aby se nezapomnělo):
1/ u všech záznamů CBA001 
2/ u záznamů importovaných od 5.11.2015 bez ohledu na siglu

**Comment by Martin-Novacek-csCZ** [comment]
Úprava v DB:
Odmazána hodnota specdruh u záznaml zaldate >= 5.11.2015 a specdruh = ZL. - 718 záznamů
Odmazána hodnota specdruh u záznamů sigla1 = CBA001 a a specdruh = ZL. - 311 záznamů

Nasazena nová verze Importního programu

CSV:
nedochází k žádným kontrolám, do Relief je přenesena hodnota která je v CSV datech.


MARC-XML:
Když pole 008 obsahuje na pozici 16-17 řetězec 'xr' a pole 015a je prázdné, tak je nsatavena hodnota specdruh = ZL

UNIMARC:
Když pole 008 obsahuje na pozici 16-17 řetězec 'xr' a pole 015a je prázdné, tak je nsatavena hodnota specdruh = ZL

**Comment by helena-oks** [comment]
Chyba!! Když pole 008 NEOBSAHUJE řetězec xr!!! XR je zkratka pro místo vydání v Česku, čili toto není zahraniční literatura.

**Comment by Martin-Novacek-csCZ** [comment]
Opraveno, nasazena nová verze.
ještě s malou změnou.

V záznamech z městské knihovny (UNIMARC) se nenachází pole "008".
Obsahem by odpovídalo pole "leader"

Takže do kontrol bylo přidáno i pole "leader".

příklad záznamu:
		<record>
			<header>
				<identifier>oai:www.mlp.cz:196444</identifier>
				<datestamp>2016-01-04T06:57:08Z</datestamp>
				<setSpec>until98</setSpec>
				<setSpec>digitization</setSpec>
			</header>
			<metadata>
				<unimarc:record xmlns:unimarc="http://www.bn.pt/standards/metadata/marcxml/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bn.pt/standards/metadata/marcxml/1.0/ http://xml.bn.pt/schemas/Unimarc-1.0.xsd" type="Bibliographic">
					<unimarc:leader>     nam  22        4500</unimarc:leader>
					<unimarc:controlfield tag="001">196444</unimarc:controlfield>
					<unimarc:controlfield tag="005">20160104075708.0</unimarc:controlfield>
					<unimarc:datafield tag="100" ind1=" " ind2=" ">
						<unimarc:subfield code="a">20160104d1920^^^^|^^^0czey0103^^^^||</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="101" ind1="0" ind2=" ">
						<unimarc:subfield code="a">ger</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="102" ind1=" " ind2=" ">
						<unimarc:subfield code="a">AT</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="200" ind1="1" ind2=" ">
						<unimarc:subfield code="a">Der Goldschmied von Toledo</unimarc:subfield>
						<unimarc:subfield code="e">romantische Oper in einem Vorspiel und zwei Akten</unimarc:subfield>
						<unimarc:subfield code="f">mit teilweiser Benützung einer Erzählung E. T. A. Hoffmanns von Karl Georg Zwerenz</unimarc:subfield>
						<unimarc:subfield code="f">Musik von Jacques Offenbach</unimarc:subfield>
						<unimarc:subfield code="g">musikalische Bearbeitung Julius Stern, Alfred Zamara</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="210" ind1=" " ind2=" ">
						<unimarc:subfield code="a">Wien</unimarc:subfield>
						<unimarc:subfield code="c">Universal Edition</unimarc:subfield>
						<unimarc:subfield code="d">[ca 1920]</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="215" ind1=" " ind2=" ">
						<unimarc:subfield code="a">82 s.</unimarc:subfield>
						<unimarc:subfield code="d">20 cm</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="225" ind1="2" ind2=" ">
						<unimarc:subfield code="a">Textbuch</unimarc:subfield>
						<unimarc:subfield code="v">Nr. 6181</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="608" ind1=" " ind2=" ">
						<unimarc:subfield code="a">operní libreta</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="610" ind1=" " ind2=" ">
						<unimarc:subfield code="a">forma: text</unimarc:subfield>
						<unimarc:subfield code="a">nosič: papír</unimarc:subfield>
						<unimarc:subfield code="a">způsob vydávání: monografie</unimarc:subfield>
						<unimarc:subfield code="a">úroveň zpracování: jednoduchá</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="700" ind1=" " ind2="1">
						<unimarc:subfield code="a">Zwerenz</unimarc:subfield>
						<unimarc:subfield code="b">Karl Georg</unimarc:subfield>
						<unimarc:subfield code="f">1874-1933</unimarc:subfield>
						<unimarc:subfield code="4">070</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="701" ind1=" " ind2="1">
						<unimarc:subfield code="a">Offenbach</unimarc:subfield>
						<unimarc:subfield code="b">Jacques</unimarc:subfield>
						<unimarc:subfield code="f">1819-1880</unimarc:subfield>
						<unimarc:subfield code="4">230</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="702" ind1=" " ind2="1">
						<unimarc:subfield code="a">Stern</unimarc:subfield>
						<unimarc:subfield code="b">Julius</unimarc:subfield>
						<unimarc:subfield code="f">1820-1883</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="702" ind1=" " ind2="1">
						<unimarc:subfield code="a">Zamara</unimarc:subfield>
						<unimarc:subfield code="b">Alfred</unimarc:subfield>
						<unimarc:subfield code="f">1863-1940</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="801" ind1=" " ind2="0">
						<unimarc:subfield code="b">ABG001</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="801" ind1=" " ind2="1">
						<unimarc:subfield code="b">ABG001</unimarc:subfield>
					</unimarc:datafield>
					<unimarc:datafield tag="910" ind1=" " ind2=" ">
						<unimarc:subfield code="a">ABG001</unimarc:subfield>
						<unimarc:subfield code="b">VB 14337</unimarc:subfield>
					</unimarc:datafield>
				</unimarc:record>
			</metadata>
		</record>

**Comment by helena-oks** [comment]
Do unimarcové konverze bych nic takového nepřidávala. Tam je země vydání v úplně jiném poli : zde v ukázce je to AT=Rakousko:
AT/unimarc:subfield
/unimarc:datafield
a nevím, jestli v unimarcu dávají kód XR nebo CZ nebo CS, protože to už dávno nepoužíváme. 

Městská knihovna moc zahraniční literatury nedigitalizuje, tak nevadí, když kód nebude vůbec. U starších věcí ZL stejně není a slouží hlavně proto, aby se zahraniční věci vyseparovaly při hledání záznamů, co by měly dostat ččnb.

**Comment by Martin-Novacek-csCZ** [comment]
OK - bude platit pouze pro marcxml
Nasazena nová verze.
