### ISSUE TITLE
dotaz na xml mapování 856/911pro importní program 

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#526]
Z jedné knihovny mi přišla tato "stížnost":

... při kontrole jsem zjistila, že v "URL na titul" je místo odkazu do DK odkaz na web časopisu. Tedy z našeho záznamu první výskyt 856 s odkazem na online verzi. Přitom v dalším výskytu 856 máme odkaz do DK a hlavně - máme vyplněné pole 911. Čekala bych, že to primárně bude brát odkaz z pole 911, které se zavádělo právě kvůli RD. Nebo pokud z 856, ale tam to bude brát ten výskyt pole, kde je v podpoli y Digitalizovaný dokument. 

Pole 856 je trochu problematické, ne každý tam dává správně indikátory a uvádí podpole y, na to podmínky vázat nelze. Je-li v současnosti importní program nastaven "vezmi 856, není-li, pak 911", uvítala bych, aby to bylo obráceně: "vezmi 911, není-li, pak 856". A myslím, že pokud je více výskytů 856, neměl by program brát žádný, protože to potom zavádí...

**Comment by Martin-Novacek-csCZ** [comment]
Ano je to tak že první se vere pole 856 a teprv poté pole 911.
Není problém je prohodit.

Co se týče počtu výskytů pole 856 nebudu dělat prozatím žádné úpravy.
Pokud by to bylo potřeba vytvořte prosím nové issu kde bude popsáno, jak se s polem 856 má zacházet.

**Comment by Martin-Novacek-csCZ** [comment]
Na produkční server byla nasazena nová verze Importního programu která upřednostňuje pole 911 pžed polem 856.

**Comment by luckajirku** [comment]
Dělá to opět - viz třeba cnb000359763
