### ISSUE TITLE
Nepřepsaná jména u  funkce Nastav zpracování

### ISSUE THREAD

**Issue by nezbedova** [incad/registrdigitalizace#529]
V Profilu zpracování jsem ve Stručném popisu nahradila jméno Klíma (6x a 1x jméno Polednová) jménem Uhlíř. V tabulce se ve sloupci Human name objevuje Uhlíř. Když chci Nastavit zpracování, tak jsou tam stále původní jména.

**Comment by Martin-Novacek-csCZ** [comment]
Změna jmen v listu se projeví po restartu serveru.
Ale při použití profilu zpracování budou použity správné hodnoty, jedná se jen o špatné zobrazení názvu v listu. Můžete ho tedy použít.

Funkci upravím v další verzi tak aby načítala vždy aktuální data, nikoli předpřipravená při prvním použití listu.

**Comment by MKortus** [comment]
Lze toto issue uzavřít?
