### ISSUE TITLE
prosíme o změnu stavu v testovací verzi

### ISSUE THREAD

**Issue by Pribylova** [incad/registrdigitalizace#536]
Prosíme o změnu stavu v testovací verzi u dokumentu  - 1001386693 ze stavu dokončeno na stav ,,ve zpracování". Byli bychom rádi, kdyby změna šla provést co nejrychleji, z důvodu nutnosti testování atypického dokumentu.
Děkujeme

**Comment by Martin-Novacek-csCZ** [comment]
Stav záznamu byl změněn.
