### ISSUE TITLE
nedokončený import DG114

### ISSUE THREAD

**Issue by Pribylova** [incad/registrdigitalizace#539]
dne 4.4.2016 nedoběhl import z konta DG114
Prosím o nápravu s vysokou prioritou.
děkuji MP
Celkem záznamů:                101
Nově založených záznamů:       13
Aktualizovaných záznamů:       0
Záznamů ve stavu Revize:       1
Odmítnutých záznamů:           0
Záznamů bez RAW dat (XML,CSV): 0
---------------------------------------------------
Chyba ři zpracování dat, chyba nastala u záznamu číslo: 14
---------------------------------------------------REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         np9423520
čČNB:            cnb000085143
ISBN:            [80-85767-36-8]
ISSN:            null
Čár. kód:        1001905177
Signatura:       I 335067
Název:           Poctivý Sanderson
Autor:           Seltzer, Charles Alden
Rok(y) vydání:   1994
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000196991 - BOA001

**Comment by Martin-Novacek-csCZ** [comment]
Záznamy byly naimportovány 05.04.2016 
jako: aba001_p_dg114_20160404_2.xml

LOG:
Celkem záznamů:                88
Nově založených záznamů:       88
Aktualizovaných záznamů:       0
Záznamů ve stavu Revize:       23
Odmítnutých záznamů:           0
Záznamů bez RAW dat (XML,CSV): 0
---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         bk198002224
čČNB:            cnb000155469
ISBN:            null
ISSN:            null
Čár. kód:        1002199330
Signatura:       II 081367
Název:           Televizní technika
Autor:           null
Rok(y) vydání:   1979
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000303806 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cps19950356288
čČNB:            cnb000356288
ISBN:            null
ISSN:            [0009-0778]
Čár. kód:        1001730680
Signatura:       II 009130/R.1958.Příloha
Název:           Český bratr
Autor:           null
Rok(y) vydání:   1925-1990
Rok periodika:   1958
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000340834 - BOA001
Pr000340835 - BOA001
Pr000340836 - BOA001
Pr000340837 - BOA001
Pr000341186 - BOA001
Pr000341187 - BOA001
Pr000341188 - BOA001
Pr000341189 - BOA001
Pr000341190 - BOA001
Pr000341191 - BOA001
Pr000341192 - BOA001
Pr000341193 - BOA001
Pr000341194 - BOA001
Pr000341195 - BOA001
Pr000341196 - BOA001
Pr000341197 - BOA001
Pr000341198 - BOA001
Pr000341199 - BOA001
Pr000341200 - BOA001
Pr000341201 - BOA001
Pr000341202 - BOA001
Pr000341203 - BOA001
Pr000341204 - BOA001
Pr000341205 - BOA001
Pr000341206 - BOA001
Pr000341207 - BOA001
Pr000341208 - BOA001
Pr000341801 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         bk197003056
čČNB:            cnb000427617
ISBN:            null
ISSN:            null
Čár. kód:        1002664254
Signatura:       II 069384
Název:           Technika prostředí
Autor:           Smolík, Jan
Rok(y) vydání:   1970
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000336461 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         bk195900025
čČNB:            cnb000513265
ISBN:            null
ISSN:            null
Čár. kód:        1002824555
Signatura:       II 051300
Název:           Elektrická zařízení obráběcích strojů
Autor:           Kulda, Vojtěch
Rok(y) vydání:   1958
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000339944 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         bk193702093
čČNB:            cnb000747368
ISBN:            null
ISSN:            null
Čár. kód:        1002824560
Signatura:       II 003630/[Díl] 2
Název:           Vzpomínky. II. Vzpomínky intimní a literární
Autor:           Kalus, Josef
Rok(y) vydání:   1937
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000151499 - OSA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20010989643
čČNB:            cnb000989643
ISBN:            null
ISSN:            null
Čár. kód:        1001318156
Signatura:       II 161301
Název:           Demokracie dnes a zítra
Autor:           Beneš, Edvard
Rok(y) vydání:   1947
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000061891 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20031174505
čČNB:            cnb001174505
ISBN:            [80-7185-455-7]
ISSN:            null
Čár. kód:        1000481723
Signatura:       I 414959
Název:           Píseň písní
Autor:           null
Rok(y) vydání:   2003
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000073656 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20041241335
čČNB:            cnb001241335
ISBN:            [80-7185-565-0]
ISSN:            null
Čár. kód:        1000870391
Signatura:       I 427162
Název:           To
Autor:           Miłosz, Czesław
Rok(y) vydání:   2003
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000190154 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20031245851
čČNB:            cnb001245851
ISBN:            [80-242-1009-6]
ISSN:            null
Čár. kód:        1001083651
Signatura:       II 133026
Název:           Sfinga 5
Autor:           Huf, Hans-Christian
Rok(y) vydání:   2002
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000082738 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20021255723
čČNB:            cnb001255723
ISBN:            [80-7209-460-2]
ISSN:            null
Čár. kód:        1001082664
Signatura:       I 419063
Název:           Indiáni
Autor:           Buller, Laura
Rok(y) vydání:   2003
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000254433 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20031281607
čČNB:            cnb001281607
ISBN:            [80-7106-642-7]
ISSN:            null
Čár. kód:        1000827641
Signatura:       II 132765
Název:           Dějiny Makedonie
Autor:           Rychlík, Jan
Rok(y) vydání:   2003
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000194494 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20031283922
čČNB:            cnb001283922
ISBN:            [80-86569-49-7]
ISSN:            null
Čár. kód:        1000751397
Signatura:       I 420752
Název:           Zvířata ve Třetí říši
Autor:           Sax, Boria
Rok(y) vydání:   2003
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000195910 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20041315939
čČNB:            cnb001315939
ISBN:            [80-7341-221-7]
ISSN:            null
Čár. kód:        1000940262
Signatura:       I 428459
Název:           Černá labuti bílá
Autor:           Obrtel, Vít
Rok(y) vydání:   2004
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000306897 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20041416314
čČNB:            cnb001416314
ISBN:            [80-7218-483-0]
ISSN:            null
Čár. kód:        1001096967
Signatura:       I 431140
Název:           Dívky v sedlech. 14, Zimní prázdniny
Autor:           Bryant, Bonnie
Rok(y) vydání:   2004
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000343358 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         cpk20041447698
čČNB:            cnb001447698
ISBN:            [80-00-01393-2]
ISSN:            null
Čár. kód:        1000944124
Signatura:       I 432092
Název:           Galerie géniů, aneb, Kdo byl kdo
Autor:           Haškovec, Vít
Rok(y) vydání:   2004
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000342481 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         nkc20051572265
čČNB:            cnb001572265
ISBN:            [80-204-1227-1]
ISSN:            null
Čár. kód:        1000906480
Signatura:       I 441210
Název:           Kroniky Světakraje. Kniha třetí, Zkáza létajícího města
Autor:           Stewart, Paul
Rok(y) vydání:   2005
Rok periodika:   
Část/Díl/Ročník: III.

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000298600 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         nkc20061660844
čČNB:            cnb001660844
ISBN:            [80-204-1402-9]
ISSN:            null
Čár. kód:        1001380739
Signatura:       I 450185
Název:           Kroniky Světakraje. Kniha čtvrtá, Šerolichotníkova kletba
Autor:           Stewart, Paul
Rok(y) vydání:   2006
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000298603 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         nkc20081796643
čČNB:            cnb001796643
ISBN:            [978-80-253-0560-7]
ISSN:            null
Čár. kód:        1001665286
Signatura:       I 477021
Název:           Fotbaloví divoši. Vanesa Neohrožená
Autor:           Masannek, Joachim
Rok(y) vydání:   2008
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000137499 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         nkc20081806195
čČNB:            cnb001806195
ISBN:            [978-80-7362-552-8]
ISSN:            null
Čár. kód:        1001679502
Signatura:       I 473372
Název:           Dívky v sedlech. 28, Náročná zkouška
Autor:           Bryant, Bonnie
Rok(y) vydání:   2008
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000343584 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         nkc20081820299
čČNB:            cnb001820299
ISBN:            [978-80-7185-939-0]
ISSN:            null
Čár. kód:        1001854521
Signatura:       I 482194
Název:           Mášeňka
Autor:           Nabokov, Vladimir Vladimirovič
Rok(y) vydání:   2008
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000155173 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         nkc20091961197
čČNB:            cnb001961197
ISBN:            [978-80-86212-60-9, 978-80-86212-02-9 :]
ISSN:            null
Čár. kód:        1001712891
Signatura:       II 157938
Název:           Toulky světem bájí, aneb, S rozhlasem po stezkách mytologie
Autor:           Cincibus, Josef
Rok(y) vydání:   2009
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000160316 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         nkc20091990342
čČNB:            cnb001990342
ISBN:            [978-80-7190-555-4]
ISSN:            null
Čár. kód:        1001710403
Signatura:       I 491372
Název:           Krůček od propasti
Autor:           Francková, Zuzana
Rok(y) vydání:   2009
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000252796 - BOA001

---------------------------------------------------
REVIZE: duplicitní čČNB
SIGLA:           ABA001
Pole001:         nkc20092011592
čČNB:            cnb002011592
ISBN:            [978-80-254-6043-6]
ISSN:            null
Čár. kód:        1001977271
Signatura:       I 492695
Název:           Dračí královna
Autor:           Skalová, Sylvie
Rok(y) vydání:   2009
Rok periodika:   
Část/Díl/Ročník: 

Seznam záznamů v RD.CZ proti kterým byla nalezena duplicita:
Pr000322260 - BOA001

---------------------------------------------------
