### ISSUE TITLE
chybějící záznamy v uživatelském registru - naléhavé!!

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#541]
6.4.2016 byla naimportována (automatem) dávka 18 záznamů. Tyto záznamy nejsou vyhledatelné v uživatelském rozhraní.
Příklady: 
Hnilota národů
Sagen aus dem Joachimsthaler Bezirke

Vyhledat lze pouze 1 záznam, který jsem online aktualizovala později.
Prověřila jsem namátkou, že ani jiné importy z několika dnů před tímto datem až dosud zřejmě nejsou v uživatelském RD zachyceny! Půjde o velké množství dat.

Prosím zjistit příčinu, proč se RD neaktualizuje, a co nejrychleji zajistit plnohodnotnou aktualizaci.

**Comment by albertoh** [comment]
Fast byl v nestabilnim stavu. Opraveno
