### ISSUE TITLE
doplnění financování ABA004

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#548]
1/ Prosím spustí následující příkazy pro doplnění financování:

update rlf_nkp_digital.predloha set edidate='01.08.2016',ediuser='heldvor',financovano='iop' where financovano is null and sigla1='ABA004' and zaldate > '01.01.2012' and zaldate < '01.01.2015';

update rlf_nkp_digital.predloha set edidate='01.08.2016',ediuser='heldvor',financovano='iop-ndku' where financovano is null and sigla1='ABA004' and zaldate > '01.01.2015' and rokvyd > '1900';

2/ Prosím drobnou úpravu v importním programu: doplňovat financování "iop_ndku" podle stejné zásady platné pro ABA001 (uvedeno v issue 503), též pro ABA004.

tedy: je-li sigla ABA004 (na velikosti písmen nezáleží) a suffix ve jménu souboru začíná "dg" - doplňovat financování "iop-ndku"
(rok vydání nehraje roli, zde rozhoduje suffix)

**Comment by MKortus** [comment]
Dobrý den,
bod 1:
posílám pro kontrolu počty záznamů pro jednotlivá SQL. SQL jsem mírně pozměnil.
SQL jsem zatím nespustil, počkám na odsouhlasení počtů, zatím jsem provedl jen kontrolní select.

update rlf_nkp_digital.predloha set edidate=to_date('01.08.2016','dd.mm.yyyy'), ediuser='heldvor', financovano='iop' where financovano is null and sigla1='ABA004' and zaldate >= to_date('01.01.2012','dd.mm.yyyy') and zaldate < to_date('01.01.2015','dd.mm.yyyy');
jedná se o 265 záznamů

update rlf_nkp_digital.predloha set edidate=to_date('01.08.2016','dd.mm.yyyy'), ediuser='heldvor', financovano='iop-ndku' where financovano is null and sigla1='ABA004' and zaldate >= to_date('01.01.2015','dd.mm.yyyy') and rokvyd > '1900';
jedná se o 323 záznamů

bod 2: importní soubor upravíme dle požadavku.

**Comment by helena-oks** [comment]
Počty víceméně souhlasí (RD se doplňuje, také občas edituje či maže online).  Ale s ohledem na přibývající záznamy, které by bylo poté třeba opět sql příkazem doplnit, bude asi lepší nejdřív upravit importní program a pak spustit příkazy.

**Comment by MKortus** [comment]
Data upravena (646 záznamů celkem), nový importní program nahrán.
