### ISSUE TITLE
aktualizace info pro informační stránky

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#549]
Prosím o prověření, zda na https://github.com/incad/registrdigitalizace/wiki/WebServices je aktuální popis webové služby - pokud vím, webservice se upravovala...

Taky bych uvítala písemnou informaci k tomu, jak funguje nástroj "kontrola duplicit" v uživatelském rozhraní, abych to přidala do nápovědy.

**Comment by pavelkocourek** [comment]
Dobrý den, 
webová služba má aktuální popis - parametr POLE 001 doplněn.

Do nápovědy dejte prosím:
Funkce "Kontrola duplicit", ve vyhledávacím rozhraní Registru digitalizace je určena pro rychlé vyhledání pomocí čárového kódu. Načtení kódu čtečkou do vyhledávacího pole spustí standardní dotaz a kurzor se vrátí do vyhledávacího pole pro načtení dalšího kódu.

**Comment by helena-oks** [comment]
Ještě prosím o upřesnění k té kontrole duplicit, jak funguje. Zřejmě podle čárového kódu najde záznam v katalogu, z jeho údajů vytvoří dotaz a zjistí, jestli takový dokument je v RD.

1/ funguje to jen pro NK, tj. hledá to jen v bázi NKC? Pokud by to chtěli použít v MZK, KNAV apod., co je k tomu třeba? Nebo to pozná podle IP adresy, do jaké báze se má podívat?

2/ podle jakých údajů ze záznamu hledání probíhá? autor+název+rok, nebo také ččnb, issn ap.?

Ze stručné nápovědy (po kliknutí na Kontrola duplicit) věci neznalý uživatel rozhodně nepochopí, že přes čárový kód dokumentu ve svém fondu (!) zjistí, zda jiná knihovna tento dokument (samozřejmě s jiným čárovým kódem) do RD nenahlásila... Ale pokud to slouží jen pro NK, bylo by dobré to tam napsat.

**Comment by helena-oks** [comment]
Žádám odpověď na své dotazy ze srpna.

**Comment by MKortus** [comment]
Předpokládám, že toto issue mohu uzavřít, Myslím že jsem tenkrát odpovídal emailem.
V každém případě jsme kontrolu duplicit konzultovali například minulý týden.

**Comment by MKortus** [comment]
Pro jistotu ještě dokomentuji:
Hledání duplicit funguje pro všechny knihovny stejně.
Ve vlastní knihovně se hledá pomocí: ČarovéhoKódu, Pole001, Ččnb, ISSN a ISBN v několika krocích. K tomu můžou být doplněna další pole, jako Část, ČísloPeriodika či RokPeriodika pokud jsou vyplněny. Kroky jsou vidět v rozhodovacím schématu. Která varianta hledání se použije záleží na vyplnění příslušných polí, neprohledává se podle všech možností, ale jen jednou z variant. Jedinou vyjímkou je čarový kód.
Pokud záznam nebyl nalezen ve vlastní knihovně, probíhá hledání v záznamech ostatních knihoven (s vyloučením vlastní knihovny), kde se hledá podle Ččnb, ISSN a ISBN podle vyplnění těchto polí (dle schématu). Hledá se postupně podle všech tří polí. Pokud nebyl nalezen shodný záznam hledá se podle PříjmeníAutora, ČástiNázvu a RokuVydání, opět ale jen mimo vlastní knihovnu.
Pomocí čarového kódu se vyhledává pouze ve vlastní knihovně.

**Comment by pavelkocourek** [comment]
Funkce "Kontrola duplicit", ve vyhledávacím rozhraní Registru digitalizace je určena pro rychlé vyhledání pomocí čárového kódu. Načtení kódu čtečkou do vyhledávacího pole spustí standardní dotaz a kurzor se vrátí do vyhledávacího pole pro načtení dalšího kódu.

Postup: 
a)	uživatel zadá s použitím čtečky „Čárový kód“  
Funkce se hodnotou zeptá na  http://aleph.nkp.cz/X?base=nkc&op=find 
b)	Systém obdrží  MARC záznam 
c)	Použije pole „Hlavní název“ (varfield[@id='245']/subfield[@label='a')  jako dotaz do indexu RDCZ
d)	Zobrazí standardní výsledky RD

Komentář ať prosím doplní Ivan Ljubka - jako zadavatel a uživatel.

**Comment by helena-oks** [comment]
Po dohodě s panem Ljubkou prosíme o změnu textu pod linkem na hlavní obrazovce z "kontrola duplicit" na "test duplicity (pro NK ČR)" . V případě, že by se totéž připravilo pro MZK, by se změnil obsah závorky.  Text, který se pak nad okénkem pro zadání čk objeví, bych také upravila: "Zadáním čárového kódu dokumentu z fondu NK proběhne test na existenci podobného dokumentu v RD podle slov z názvu". Nápovědu na informačních stránkách dodělám.

**Comment by albertoh** [comment]
Opraveno
