### ISSUE TITLE
doplnění URL přes sql dávky

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#551]
Prosím aktualizovat záznamy podle příkazů v příloze. Vzhledem k velkému počtu bych doporučovala soubor rozdělit tak na 3 menší. A taky pro jistotu zachovat zálohu stavu před akcí. 
[mzk_bez_url.txt](https://github.com/incad/registrdigitalizace/files/442048/mzk_bez_url.txt)

**Comment by MKortus** [comment]
Dobrý den,
hotovo. Všech 8209 záznamů upraveno. Dělal jsem to po 1000 záznamech.
Původní data měněných sloupců (plus pole idcislo) jsou uložena v tabulce predloha_20160829.

S pozdravem Marek Kortus

**Comment by lucka-pavlova** [comment]
Hotovo
