### ISSUE TITLE
nový přispěvatel

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#552]
Potřebuji zařadit siglu HOE801 jako nového přispěvatele. Do seznamu sigel  (DL sigla) jsem siglu přidala. Dřív, kdykoli jsem to udělala, objevila se sigla druhý den v nabídce při vytváření nového přispěvatele, tentokrát tam není.

**Comment by MKortus** [comment]
Dobrý den,
kontroloval jsem možnost zadání zmíněné SIGLY a dnes se mi tato hodnota nabízí. Možná jen neproběhl noční restart a proto tato možnost je dostupná až dnes.

**Comment by helena-oks** [comment]
Děkuji za prověření, již jsem přispěvatele vytvořila.
