### ISSUE TITLE
díra v nastavení importního programu?

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#555]
Prosím o prověření mechanismů importního programu - viz popis situace níže.

Záznam MZK, který má RD číslo Pr000290280 (National Gallery Londýn), byl omylem poslán do RD 2x (pokaždé jako probíhající digitalizace), jednou 4.8.2015 (BOA001_P_150804.xml) a podruhé 11.10.2016 (BOA001_P_161011.xml). Podruhé měl záznam navíc pole 856, což podle pravidel mít nesměl (ale nevím, zda se měl v tom případě zcela vyřadit, nebo se mělo pouze odstranit pole 856). Podruhé měl být odmítnut a objevit se jako vyřazený z důvodů, že již v RD je - shodovalo se jak pole001, tak čárový kód (údaje, které jsou pro zjišťování vlastní duplicity klíčové). Ve výpisu odmítných nebyl, nicméně v RD je stále pouze jeden záznam a jak já, tak pracovníci MZK jsme přesvědčeni, že jsme duplicitu v RD nemazali.

Z hlediska RD by to bylo v pořádku, ale pokud záznam není ve výpisu z importu jako odmítnutý (nebo jako potenciální duplicita), neřeší to pracovníci digitalizace a tudíž zdigitalizují duplicitně. Je možné, že byl záznam vyřazen z nějakého zvláštního důvodu a chybou programu se ve výpisu neobjevil?

**Comment by MKortus** [comment]
Dobrý den,
prohlížel jsem logy a tento záznam byl správně zpracován a odmítnut. Viz:
Záznam nebyl importován, odpovídající záznam v RD.CZ Pr000290280 - BOA001 měl vyšší nebo stejný stav záznamu: 
SIGLA:           BOA001
Pole001:         000775978
čČNB:            cnb001412920
ISBN:            [80-242-1282-X]
ISSN:            null
Čár. kód:        2610253243
Signatura:       3-1152.884
Název:           National Gallery Londýn
Autor:           null
Rok(y) vydání:   2005
Rok periodika:   
Část/Díl/Ročník: 

Toto je část logu ze souboru: 20161011111520_BOA001_P_161011.xml.log
Předpokládám, že tedy došlo k přehlídnutí tohoto záznamu. Nebo Vám tento log nedorazil?
Jednalo se o čtvrtý vypsaný záznam.

**Comment by helena-oks** [comment]
Omlouváme se za obtěžování: pokud jde o RD, vše je zjevně OK a proč došlo k duplicitní digitalizaci, těžko říct. 

K přehlédnutí došlo u mně a zřejmě i v MZK proto, že jsme nějak očekávali jediný soubor od MZK v příslušném dni, když jsme v agendě Importy hledali. A tam byl ještě soubor 20161011220728_BOA001_P_161011-b.xml.log, který pochopitelně tento záznam jako odmítnutý neobsahoval.

Děkuji, možno uzavřít.

**Comment by helena-oks** [comment]
Z MZK předávám k tomuto problému další dotaz - tentokrát ohledně webservice:

Pořád to nevysvětluje ten problém duplicity, kterou nemohlo způsobit uživatelské chování. Potřebujeme vědět, abychom odhalili jádro toho problému, v jakém stavu funkčnosti byl registr a co případně odpověděl na dotaz  WF NDK 13.10.2016 7:10, kdy podle evidence WF NDK byl načten č.k. 2610253243.  Musel jít v tento okamžik do RD  z WF NDK dotaz, zda-li  tento svazek může založit do digitalizace NDK a nebo ne, ale protože to prošlo, byla v tento okamžik do digitalizace vložena duplicita. Pokud toto budeme vědět, tak potom může být chyba i na straně programátorů WF NDK.

Doplňuji, že dotaz přes webservice byl z workflow NDK poslán z MZK. Jinak já o fungování webservice nic nevím. Dá se něco zjistit z jejích logů? V RD musel být v té době jeden záznam k tomuto čárovému kódu (se statusem ve zpracování).

**Comment by MKortus** [comment]
Dobrý den,
podle logů WS byla aktivní, ale už není logováno co na dotaz odpověděla.  WS nekomunikuje s Reliefem, ale přímo s databází. Vzhledem k předchozím ale i následným dotazům, nebyl problém s připojením k databázi, to by se v logu projevilo.
Záznam v Reliefu v té době byl založen, to je vidět z datumu založení, které je v roce 2015.

**Comment by MKortus** [comment]
Lze toto issue uzavřít?

**Comment by helena-oks** [comment]
Možno uzavřít, problém duplicit se bude řešit jinde a jinak.
