### ISSUE TITLE
nový přispěvatel a DL sigla

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#556]
Včera jsem přidala do DL Sigla novou siglu TRE801, očekávala jsem, že tedy dnes bude v nabídce pro přidání přispěvatele, ale není tam. Už se to stalo jednou. Nedal by se ten mechanismus upravit tak, aby se sigla v agendě přispěvatel nabídla ihned po přidání do DL Sigla? Zdržuje to mě i knihovnu, když nemůžu akci dokončit najednou, a ještě navíc někdy musím žádat o aktivaci...

**Comment by MKortus** [comment]
Dobrý den, jestli se nepletu, dynamické listy se obnovují (znovunačítají) pouze při startu serveru a ten naposledy proběhl 13.11, proto nemáte tuto Siglu dostupnou. Restart serveru je nastaven pouze na neděli v 5 hodin 10 minut ráno.

**Comment by helena-oks** [comment]
To je tedy horší než jsem čekala a tím spíš bych prosila, jestli se s tím nedá něco dělat. Třeba aby mi to umožnilo založit přispěvatele, i když sigla v DL není. (S agendou přispěvatele pracují pokud vím importy, DL je potřeba pro online práci).  Z knihovny si zažádali o siglu v pátek, to jsem nebyla v práci, včera jsem udělala krok 1 a dnes jsem chtěla udělat krok 2. Takhle abych se jim omlouvala, že musejí víc než týden čekat, než budou moci poslat data!

**Comment by MKortus** [comment]
Můžeme změnit metodu, která sestavuje zdroj pro kombo, tak aby podávala vždy aktuální data. Bude to vyžadovat zásah do zdrojového kódu příslušné agendy.  Celkový čas na úpravu, testování a nasazení na produkci odhaduji cca 1 MD ve vývojových pracích. Zjistíme jestli bude potřeba samostatná objednávka.

**Comment by pavelkocourek** [comment]
Dobré odpoledne, zvažte prosím, zdali má význam úpravu provézt. Obsah DL se zas tak často nerozšiřuje.

**Comment by helena-oks** [comment]
Dobře, smířím se s tím a knihovny budu upozornovat, že si týden počkají.
