### ISSUE TITLE
smazání chybové dávky

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#558]
Prosím smazat záznamy BOA001 v rozmezí Pr000421504 až Pr000421866. Mělo by to být 363 záznamů z dávky 20161209130026_BOA001_H_161209. (3 záznamy z dávky, které nebyly nové, ale aktualizovaly se, si vyřeší v MZK sami).

**Comment by MKortus** [comment]
Dobrý den,
smazáno (363 záznamů) i s podřízenými záznamy v: nepisbn (4), nepccnb (2) a tabvarnazev (38)
