### ISSUE TITLE
nová sigla pro automatizované importy

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#562]
Prosím zařadit do importního programu siglu aba009, tj. nastavit, aby byl vybírán adresář aba009r. 

(Nedalo by se to v programu upravit tak, aby se koukal do všech podadresářů na ftp.nkp.cz/rd/? Pak bychom to nemuseli pokaždé řešit. Pokud by to trvalo déle, přidejte zatím tento adresář, knihovna už má připravená data.)

**Comment by MKortus** [comment]
Dobrý den,
vzhledem k tomu, že se pro každý zdroj musí nastavit několik parametrů, tak se obávám že automatické procházení adresářů možné není. Navíc zde existuje několik typů importních souborů (CSV, MarcXML, atd...), kde pro každý typ je nastavení rozdílné,
Dále bych potřeboval vědět, jaká nastavení mají být pro tento zdroj. Předpokládám, že nastavení bude podobné například "ABA004R".
Dále potřebuji vědět jak často se má spouštět, předpokládám 2xdenně.

V adresáři jsem momentálně žádný soubor nenašel.

**Comment by helena-oks** [comment]
Předpokládala jsem, že všechny individuální sigly mají nastavení stejné až na abg001r a cba001r, co mají trochu jiné xml.  Vesměs posílají jen xml, a to standardní marc21. Výjimkou je možná ještě adresář skc001r, kam já umístuju všechny soubory od knihoven, co pro ně není zvláštní adresář (xml i csv). Nebo je tomu jinak? 

Oprávněně se liší frekvence prohlížení - s výjimkou aba001r, aba004r, boa001r, aba007r nejspíš bohatě stačí 2x denně (též pro aba009r). V jakých časech to běží?

Knihovna pošle soubor do adresáře teprve až jí dám vědět, že je nastavení hotové, aby brzo dostala zprávu, jak to dopadlo.

**Comment by MKortus** [comment]
Dobrý den,
potřeboval bych alespoň vzorek dat, abych mohl otestovat, že načtení proběhlo v pořádku.
V současnosti je 24 nastavených zdrojů. Pravděpodobně se nastavení u některých ze zdrojů opakuje. Přesto je každý nastaven samostatně.

Můžete mi prosím poslat vzorek dat, abych vyzkoušel import u nás?

Děkuji Kortus

**Comment by helena-oks** [comment]
Dala jsem na ftp do příslušného adresáře ukázku, co mi poslali.

**Comment by MKortus** [comment]
Zdroj ABA009 nastaven a ukázkový soubor po restartu automaticky naimportován.
