### ISSUE TITLE
výmaz záznamů

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#564]
Prosím o vymazání záznamů v příloze - se všemi připojenými údaji.
[mlpdup1_id.txt](https://github.com/incad/registrdigitalizace/files/854236/mlpdup1_id.txt)

**Comment by MKortus** [comment]
Dobrý den,
smazáno:
  59 neplatných ccnb,
    6 nepletných isbn,
    0 neplatných issn,
  11 záznamů v tabVarNazev
359 záznamů v předloze.

**Comment by helena-oks** [comment]
Dobrý den

a díky. Ale z vaší zprávy jsem si uvědomila, že možná nebylo žádoucí smazat i ty neplatné údaje z přidružených tabulek, protože mohly být napojené na jiné, nemazané záznamy. Dá se nějak zjistit, jestli byly? Pokud vím, záloha se každý den přepisuje, takže když to nezjistíme hned, už to nepůjde. Šlo by ty údaje z dalších tabulek vypsat ze zálohy?

Mrzí mě, že jsem to nedomyslela…

Helena Dvořáková

**Comment by MKortus** [comment]
Dobrý den,
vzhledem k tomu, že je tam přímá vazba na mazané záznamy (přímo přes ID), tak myslím že nemohly být navázané na jiné záznamy. Navíc mám zálohu všeho co jsem mazal v pomocných tabulkách, takže je možno se k tomu kdykoliv vrátit. Tedy dokud tyto záložní tabulky nesmažu.
