### ISSUE TITLE
výmaz záznamů

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#565]
Prosím o vymazání záznamů v příloze - stejně jako v minulém případě. (Možná s kontrolou, že jde vesměs o záznamy sigly KLG001).
[klg-smazat.txt](https://github.com/incad/registrdigitalizace/files/871833/klg-smazat.txt)

**Comment by MKortus** [comment]
Dobrý den,
smazáno 43 záznamů z předlohy (všechny od jedné sigly), 22 z nepccnb a 6 z tabvarnazev. Zálohy vytvořeny.
S pozdravem Marek Kortus
