### ISSUE TITLE
výmaz čárového kódu ze záznamů Městské knihovny

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#566]
Prosím o výmaz pole carkod = čárový kód ze záznamů MěK (mlp), tj. kde sigla1=ABG001. Viz issue 388, poslední poznámka.

(Potvrzení od paní Hartmannové z MěK:  Můj souhlas k vymazání čk určitě máte, ať se toho zbavíme a je klid.)

**Comment by MKortus** [comment]
Dobrý den,
čarkový kód pro ABG001 vymazán. Jednalo se o 5235 záznamů. (celkem je v tabulce PREDLOHA 8838 záznamů)
