### ISSUE TITLE
neproběhl import - chyba při zpracování dat

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#568]
Soubor aba001_p_nkp551.xml posílaný v pátek 19.5. se importoval jen zčásti, import havaroval na záznamu č. 12 a poté se import zacyklil. Prosím zjistit příčinu (jaká chyba v zázn. č. 12) a buď znovu poslat celé, nebo vše kromě inkriminovaného záznamu, nebo vše následující po onom záznamu. 

Log:
Celkem záznamů:                207
Nově založených záznamů:       11
Aktualizovaných záznamů:       0
Záznamů ve stavu Revize:       0
Odmítnutých záznamů:           0
Záznamů bez RAW dat (XML,CSV): 0
---------------------------------------------------
Chyba ři zpracování dat, chyba nastala u záznamu číslo: 12
---------------------------------------------------

**Comment by MKortus** [comment]
pravděpodobně způsobeno nedostupností Reliefu.
Při opětovném spuštění naimportováno bez problémů.
