### ISSUE TITLE
zobrazení již zrušených záznamů na uživatelském webu

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#569]
Uživatelům se stále zobrazují záznamy, které jsem v reliefu zrušila již před časem - jsou bez údajů o vlastníkovi (původně duplicity KLG001). Viz obrázek (týká se všech svazků s červeným čtverečkem, správný zachovávaný záznam je souborný z let 1928-31 -zelený). Viz obrázek
![bilianova](https://user-images.githubusercontent.com/13746425/27074078-49993b32-5026-11e7-9f16-a93be047c7a1.jpg)

**Comment by MKortus** [comment]
bude provedena kompletní reindexace. Domluveno s A.H.
