### ISSUE TITLE
Úprava tabulky předloh v Detailu, ukotvení záhlaví, dvoustupňové třídění

### ISSUE THREAD

**Issue by lucka-pavlova** [incad/registrdigitalizace#571]
Popis z e-mailu od p. Ljubky:
Při kliknutí na detail bych uvítal zvětšení tabulky (seznamu předloh) a rozhodně ukotvit záhlaví (rychlejší výběr pro řazení) seznamu předloh. Ideální stav by bylo použití dvoustupňového řazení (stačil by u vlastníka a roku) Ve starém RD se v NK dost používá funkce, kdy si odfiltruji knihovnu a vidím seřazené roky (jasně nebyly dynamicky generovány, ale dobrá orientace při zjišťovačkách). Možnost řazení dle vlastníka  (především u periodik) při dohledávání nebude příliš využitelná, protože dojde k úplnému rozhození posloupnosti let (chápu proč, ale to je málo

**Comment by pkudela** [comment]
Vetsina z popisu je hotova, zvetseni tabulky pri soucasnem gridu, bohuzel neni mozna. Prosim zkontrolujte, je nasazena nejnovejsi aktualni verze a pripadne issue zavrete.

**Comment by helena-oks** [comment]
Já myslím, že toto řešení je zcela vyhovující, ale vyjádřit se musí též pan Ljubka.

**Comment by pavelkocourek** [comment]
Zavřeno na schůzce RDCZ 1.2.2017
