### ISSUE TITLE
Chování "Vymazat filtry"

### ISSUE THREAD

**Issue by lucka-pavlova** [incad/registrdigitalizace#572]
Popis z e-mailu p. Dvořákové:
zkoušela jsem akci „vymazat filtry“. Tím se dostanu na úplnou databázi, což asi uživatel nečeká, spíš čeká, že se provede ten jeho dotaz bez filtrů. Takže bych tu variantu s vymazáním filtrů nejraději vůbec nenabízela (tím bude hláška i kratší). Nebo  by to šlo dát takto: „Můžete/Nechcete zkusit dotaz formulovat jinak (a pozor na nastavení filtrů)“.

**Comment by helena-oks** [comment]
Upřesnění: jde o hlášku v případě, že nebylo nalezeno nic.

Upozornění! Nalezeno 0 záznamů, hledání podobných záznamů též bez úspěchu. **Můžete zkusit dotaz formulovat jinak nebo vymazat všechny filtry.** 

Pro nalezení "podobných" záznamů již hláška podle mého návrhu upravena byla:
Upozornění! Nalezeno 0 záznamů, nabízím podobné záznamy. Nechcete zkusit dotaz formulovat jinak nebo vymazat filtry? 

Ale v obou případech bych NEnechávala slovo vymazat jako klikací=funkční. Ať každý začne znovu od začátku.

**Comment by helena-oks** [comment]
Zjistila jsem dalším testováním, že u negativních výsledků tu musí být implicitně nastaveno "vymazat všechny filtry". Při negativním výsledku není možné nijak smazat "filtr" vytvořený předchozím dotazem z jednotlivých polí a pak jakýkoli další dotaz má nulový výsledek, aniž by uživatel tušil, že tam tento filtr má! Situace, že nejdřív něco neúspěšně hledám přes jednotlivá pole a potom v upravené formě přes základní okénko, může běžně nastávat!

**Comment by pavelkocourek** [comment]
Při Novém dotazu (do hlavního searchboxu) smazat hodnoty v Rozšířeném vyhledávání (např. Název)

**Comment by pkudela** [comment]
Timto chovanim si nejsem jist, ted jsem to testoval a prijde mi logicke, ze filtr, ktery jsem si zvolil v rozsirenem hledani mohu kombinovat s dotazem z hlavniho vyhledavaciho boxu, tim mohu zuzovat/konkretizovat vysledky. Navic proto je tam box "Pouzite filtry", kde vidim zvoleny filtr z rozsireneho hledani, kde je vypsane i pole, ktere jsem zvolil napr. "Název: nemcova". Pokud tedy zkombinuji dotaz z rozsireneho hledani s dotazem z hlavniho searchboxu, budu v pouzitych filtrech videt obe omezeni, pokud zadam volbu "zařadit dotaz jako filtr" viz. screenshot nize. Stejne to mame resene v jinych aplikacich napr. digiarchiv a jine. Uzivatelsky mi to prijde takto spravne. Naopak, pokud bychom zadana omezeni z rozsireneho hledani pri zadani query do hlavniho searchboxu automaticky zrusili, bylo by to dle meho pro uzivatele pri nejmensim matouci. Veskere filtry z rozsireneho hledani a jine mohu pohodlne zrusit z boxu "Pouzite filtry". Akorat bych v cestine zmenil nazev tohoto boxu z "Nastaveni filtru" na zminovane "Pouzite filtry", stejne jako je to v anglickem prekladu.
------

![image](https://user-images.githubusercontent.com/16591052/35737586-53104110-082c-11e8-84ce-531206d5a2ca.png)

**Comment by pkudela** [comment]
Nasadil jsem novou verzi -> http://sluzby.incad.cz/rdcz/home. Prosli jsme Vas dokument a upravili tak, aby aktivni filtry byly vzdy videt a zruseni aktivnich filtru tak bylo vzdy dostupne. Muzte zkusit na dotazu, ktery vraci 0 vysledku -> http://sluzby.incad.cz/rdcz/results;q=krakatit;start=0;rows=15;sort=score%20desc;filters=%5B%5D;adv=%7B%22title%22:%22havlicek%22,%22autor%22:%22%22,%22rokvyd%22:%22%22,%22isxn%22:%22%22,%22ccnb%22:%22%22,%22signatura%22:%22%22,%22carkod%22:%22%22,%22cislordcz%22:%22%22,%22pole001%22:%22%22,%22vydavatel%22:%22%22,%22can%22:%22%22%7D;collapse=cnb_collaps
Jinak premyslim, proc nedavat query vzdy jako aktivni filtr bez moznosti zaskrtnuti. Nevim, jestli tato volba ma v teto aplikaci nejaky vyznam, ale v ostatnich aplikacich na kterych delame davame vzdy query do aktivnich filtru, aby mel uzivatel prehled a mohl query jednim klikem vzdy zrusit.

**Comment by helena-oks** [comment]
Zobrazení použitých filtrů u všech výsledků včetně negativních v podstatě problém řeší - to si už každý uvědomí a může si ty filtry zrušit.  Pak by asi mohl být i předchozí dotaz nastaven implicitně jako filtr a zaškrtávací okénko tam být nemusí.  (Dalo by se to vrátit, když by byla negativní uživatelská odezva? RD je možná využíván trochu jinak než jiné aplikace.) Pokud zvolíme toto řešení, chtěla bych souhlas pana Ljubky.

**Comment by pkudela** [comment]
Ano, vratit se do da, to neni problem.

**Comment by pkudela** [comment]
Muzeme tedy ten box se zarkrtavacim checkboxem skryt? Cili implicitne bude vzdy query ve filtrech.

**Comment by helena-oks** [comment]
Jsem pro to skrýt a nastavit jak říkáte, ale pan Ljubka to zatím neviděl a nejspíš to podrobné hledání dost používá.

**Comment by pkudela** [comment]
Tak to radeji nechame zatim byt jak to je, mohu toto issue zavrit? @helena-oks

**Comment by helena-oks** [comment]
Kdyby to nedalo moc práce potom to vrátit k současnému stavu, byla bych pro nastavit to podle vašeho návrhu (se skrytým checkboxem a implicitním filtrem z dotazu) a nabídnout to panu Ljubkovi. Když bude zásadně namítat, vrátíme to. Popis chování bych pak přidala do helpu. Můžete napsat na ivan.ljubka@nkp.cz, ať to pořádně otestuje a dá vám zprávu (+ mně v kopii)? Bez zvláštního upozorňování, co se tam změnilo... Dnes už nebudu na mailu ani na webu.

**Comment by pkudela** [comment]
OK, pripravime to.

**Comment by albertoh** [comment]
provedeno, nasazeno
