### ISSUE TITLE
Homepage - vlastník - úprava vzhledu

### ISSUE THREAD

**Issue by lucka-pavlova** [incad/registrdigitalizace#573]
Popis z e-mailu p. Dvořákové:
potřebovalo by to větší mezeru mezi siglu a název

**Comment by pkudela** [comment]
Hotovo, zvetseni bylo mozne o 3% vic uz by nevypadalo dobre s ohledem na ostatni sloupce. Prosim otestujte a pokud OK, tak issue zavrete.

**Comment by helena-oks** [comment]
Úplně OK, jen před nasazením naživo by asi mělo být implicitní řazení podle sigly.

**Comment by pavelkocourek** [comment]
Nastavit default na Sigla

**Comment by pkudela** [comment]
Hotovo, nastavena Sigla jako default razeni vzestupne, cili od A - Z. Jakmile nasadim na testovaci server,  pridam label "K testovani"

**Comment by pkudela** [comment]
Nasazena nova verze na testovaci server -> http://sluzby.incad.cz/rdcz/home

**Comment by helena-oks** [comment]
Díky, možno uzavřít.
