### ISSUE TITLE
okénko pro podrobné vyhledávání

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#574]
Prosím nahradit v novém webu v nabídce okénka pole Číslo zakázky, které se už neužívá, polem Nakladatel/vydavatel.

**Comment by pkudela** [comment]
Prosim, pridavejte ke kazdemu dalsimu issue, ktere se tyka nove aplikace modry label "Aplikace - nove vyhledavani". Tomuto issue jsem ho pridal. diky

**Comment by helena-oks** [comment]
Bylo by možné posunout tento údaj nahoru, hned za rok vydání? (Mohla jsem to napsat rovnou, omlouvám se).

**Comment by albertoh** [comment]
Opraveno

**Comment by helena-oks** [comment]
děkuji.
