### ISSUE TITLE
opravy přes sql

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#575]
Prosím spustit dávky v příloze.
[hke302_hka.txt](https://github.com/incad/registrdigitalizace/files/1204943/hke302_hka.txt)
[ccnb_dod0717.txt](https://github.com/incad/registrdigitalizace/files/1204942/ccnb_dod0717.txt)

**Comment by MKortus** [comment]
sql spuštěno.

soubor: hke302_hka.txt
4 rows updated.
1 row updated.
22 rows updated.
24 rows updated.
16 rows updated.
44 rows updated.
2 rows updated.
6 rows updated.
8 rows updated.
9 rows updated.
28 rows updated.
20 rows updated.
39 rows updated.
27 rows updated.
24 rows updated.
29 rows updated

soubor ccnb_dod0717.txt
celkem 159 záznamů, 3x2 a 1x4 záznamů
