### ISSUE TITLE
opravy url přes sql

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#577]
Prosím spustit příkazy v příloze.

**Comment by helena-oks** [comment]
[urlopr_hka001.txt](https://github.com/incad/registrdigitalizace/files/1238497/urlopr_hka001.txt)
[urlopr_pna001.txt](https://github.com/incad/registrdigitalizace/files/1238498/urlopr_pna001.txt)

**Comment by MKortus** [comment]
urlopr_hka001.txt
upraveno:  99x1 záznam, pak 17 a 33 záznamů

urlopr_pna001.txt
upraveny sql příkazy - místo "'" bylo použito ";"a místo ";" "@"
46 záznamů
17 záznamů
2 záznamy
51 záznamů
2 záznamy
37 záznamů
46 záznamů
a dále po 1 záznamu
