### ISSUE TITLE
zobrazování URL v detailech na novém webu

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#582]
Je třeba změnit zobrazování různých URL, aby bylo přehlednější u vícesvazkových monografií a seriálů. Podrobný popis + ukázka současného nevyhovujícího stavu v příloze.
[RD-předloha-digdok.docx](https://github.com/incad/registrdigitalizace/files/1418132/RD-predloha-digdok.docx)

**Comment by helena-oks** [comment]
Label mi to nedovolí přidat, prosím přidejte. Nejde jen o zobrazení, též o funkcionalitu výběru/filtrace a propojování.

**Comment by helena-oks** [comment]
Požadavky 1 a 3 z přílohy splněny. Je třeba ještě dodělat:
- Předlohy by měly být seřazené podle Rok periodika a Část/ročník, pokud se tato pole vyskytují - ať je jakýkoli vlastník (tj. v zobrazení nesdružovat podle vlastníka) = pož.2
- Linky na digitální dokumenty: u PERIOdik NEDÁVAT znovu odkazy z pole URL, dávat jen odkazy z polí URLTITUL, URLTITNK + URL na titul ze sklizně (pokud se ho podaří propojit) = pož. 4 

Ukázkový záznam pro testování: Zlatá Praha

**Comment by helena-oks** [comment]
Řazení již OK. 

Linky na digitální dokumenty po rozkliknutí na "Digitální dokument"  (nikoli v Předlohách) zatím v případě periodik v patřičném výběru nejsou.  
Upřesňuji: zde se mají zobrazit všechny(!) URL, která jsou v uvedených polích + URL propojené z tabulky Digobjekt, jen zde NEmají být URL z pole "URL" v Předloze, neboť ty jsou zobrazitelné z Předloh a bylo by jich moc. Platí pouze pro periodika!

**Comment by albertoh** [comment]
Dobry den,

zrejme nerozumim spravne zadani. Muzete mi napsat par prikladu, kde to se nezobrazi spravne?

Dekuju

**Comment by helena-oks** [comment]
Příklad1. Zlatá Praha, cnb001302356 - jsou přítomny odkazy v polích URLTITUL a URL.  URLTITUL je pro všechny ročníky stejný, tudíž se má zobrazit jen 1x, ale protože jsou tam 2 digitální knihovny, budou 2 URLTITUL.
URL je u každého svazku ABB060 a dá se k němu dostat šipkou z předlohy, proto ho do přehledu dig.dok. nechceme.  
Příklad2. Film a doba, cnb000356320 - u všech ročníků je URLTITUL a URLTITNK (samozřejmě u všech stejné) - obě URL se musejí zobrazit. 
V příloze ukázka z výstupu v tabulce - zeleně to, co má být pod dig.dokumentem. 
(z Digobjekt se asi nic nepřipojí - tam myslím zatím odkazy pro SE nejsou).
[digdok-zobrazeni.xlsx](https://github.com/incad/registrdigitalizace/files/1663756/digdok-zobrazeni.xlsx)

**Comment by albertoh** [comment]
Ted je mi jasne :)
Opraveno
Prosim o otestovani

**Comment by helena-oks** [comment]
Díky, už je to OK.
