### ISSUE TITLE
nevhodná ergonomie testu duplicit + přidat test duplicit v MZK

### ISSUE THREAD

**Issue by indrakm** [incad/registrdigitalizace#585]
Sjednocením vyhledávacího pole s testem na duplicity, došlo k tomu, že přibylo další kliknutí navíc (načtení č.k.) a poté kliknutí na pole test duplicity (při stovkách knížek docela velká komplikace). Kromě problému s tím, že běžně nakonfigurované čtečky mají enter, se hned po načtení č.k. vyhledá nikoliv podle testu duplicity (tj. načtení názvu z katalogu), ale podle toho, zda je č.k. v databázi RD. Navíc není možné využít funkční klávesu (vracení se jako u stávající verze RD).

Návrh řešení: Navrhujeme (tak jak je ve stávající verzi) přidat samostatné pole pro test duplicity, které po volbě bude aktivní, aby bylo možné okamžitě bez klikání načíst č.k. s entrem a včetně zachování vracení se pomoci funkční klávesy Backspace.  Pokud nebude řešeno samostatným polem, je možná varianta společného pole, ale po první volbě na „test duplicity“ již zůstat v  režimu testování duplicit tj. nikam nevyskakovat a jen čtečkou a entrem kontrolovat duplicity. Návrat do běžného vyhledávání pak řešit opětným stisknutím tlačítka „ test duplicit“ (pokud bude taková volba, je možné „test duplicity“ dostat z domovské stránky, aby nemátl ostatní uživatele a někam ho vnořit.

Přidat prosím i test duplicit v MZK (podklady k tomu by měly být již zaslány v dřívější době)

**Comment by Foltom** [comment]
Zdravím, prosím o dořešení Issue. Je to důležité s ohledem na testování nového vyhledávání. Díky. T. Foltýn

**Comment by albertoh** [comment]
Hotovo. Prosim o testovani

**Comment by indrakm** [comment]
otestováno, funkční, děkujeme
