### ISSUE TITLE
zobrazení Poznámky pro uživatele - starý i nový uživatelský web

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#586]
Údaj z pole Bibpoznamka se nezobrazuje v uživatelském rozhraní, asi se při nějakých úpravách ztratilo. Návěští: Poznámka. Přidat na konec bloku BIB údajů.  

Nutné! Jsou tam důležité údaje!

Totéž prosím pro nový web.

**Comment by helena-oks** [comment]
Zjistila jsem, že jste přidali Poznámku jako sloupeček u předlohy. Asi je lepší, když je tam než nahoře, jenže při větším rozlišení nebo menší obrazovce buď není vidět a  musí se rolovat, nebo přelézá ven. Viz obr. 
Bylo by možné nějak zkrátit záhlaví sloupečků (které jsou stejně buď prázdné, nebo s kratším textem), nebo některá záhlaví natvrdo rozdělit do dvou řádků? 
Návrh:  
Rok per. - do dvou řádků
Část/roč. - do dvou řádků
Číslo => Č. (téměř se nevyskytuje a každý to pochopí)
Financováno => Financ.  (tady by se taky v rámci úspory místa hodilo, jestli to jde, nedávat místo "neuvedeno" nic)
Signatura => Sign.
Čár. kód => ČK (kdo to potřebuje, ten to pochopí)
Poznámka => Pozn.

Ve starém vyhledávání už nic neupravovat.

**Comment by albertoh** [comment]
Hotovo, prosim o otestovani

**Comment by helena-oks** [comment]
Umístění poznámky ve sloupečku v Detailech je vyhovující a téměř vždy se vejde.
