### ISSUE TITLE
Bug - u periodik se nezobrazují všechny exempláře

### ISSUE THREAD

**Issue by zabak** [incad/registrdigitalizace#589]
Příklad: Světová literatura - cnb000356626
Ve starém RD se zobrazí 32 svazků MZK ve stavu hotovo a 30 svazků NK ve stavu záměru. V novém RD se zobrazí jen 32 dokončených záznamů MZK.

**Comment by Foltom** [comment]
Prosím o dořešení bugu. To samé jako o 585 - důležité pro testování. T. Foltýn

**Comment by albertoh** [comment]
Je to problem aktualnosti indexu. Az budu moc indexovat, tj, bude pristup na oracle z novych serveru, zkontroluju.

**Comment by albertoh** [comment]
Po reindexaci v novem serveru vidim celkem 62 predloh

**Comment by albertoh** [comment]
Je to opraveno. Je videt v novem serveru
