### ISSUE TITLE
nový web - změna podnázvu v hlavičce

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#590]
V NK a MZK jsme si odsouhlasili změnu podnázvu v hlavičce, aby byl výstižnější:

Místo "evidence digitalizovaných dokumentů a sledování procesu zpracování" dát "evidence dokumentů digitalizovaných v ČR".

**Comment by albertoh** [comment]
Je to v obrazku logo

**Comment by pkudela** [comment]
Jo, zitra to udelam a nasadim na testovaci server.

**Comment by pkudela** [comment]
hotovo -> http://sluzby.incad.cz/rdcz/home + je to na github
Zapomelo se jeste na anglickou verzi, Lucko, dodej presnou specifikaci anglicke verze

**Comment by lucka-pavlova** [comment]
Já bych do anglického loga dala jen :

documents digitized in the Czech Republic

@helena-oks , souhlasíte?

**Comment by helena-oks** [comment]
Anglická verze OK, takže issue zavírám.
