### ISSUE TITLE
nový web - informační stránky

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#591]
Základ pro infostránky je vytvořen, je potřeba vyřešit základní přístup a menu. Vkládám obsah mailu z 11.12.

Zatím nemám možnost vidět výsledek, jak se dostat k dílčím stránkám. Bude možné realizovat info v podobě navigačního sloupce = menu (vpravo či vlevo) + vlastního textu ve zbylém (dvousloupcovém) prostoru?  

Pak bych potřebovala vědět, do jakého souboru dát jako základ toto menu. Bude to soubor info, v němž se bude v jednom sloupci měnit obsah ? Momentálně je v „info“ totéž co v „index“. Který z těch souborů mám editovat, tj. „zbavit ho“ té části, co přijde do menu?

Ještě je třeba umístit někam obrázky, které budu natahovat do souborů, např. do souboru relief (ty jsou momentálně v adresáři relief_soubory). Pak potřebuju poradit, jak do souboru vložit link na stažení externího souboru (a ten někam umístit).

**Comment by helena-oks** [comment]
1. Dvousloupcové rozdělení je výborné, jen se potřebuju také dostat k editaci levého sloupce. Pokud to není možné, prosím upravte obsah tak, aby se jako první nabízela základní stránka "info" s popiskem "Základní informace" (není tam vůbec!).
Dále v tomto pořadí:
 "Jak zasílat data" (uvnitř je rozdělení OK, jen prosím Služba s velkým S)
"Jak získat čČNB" (ještě lepší by bylo to zařadit pod Jak zasílat data)
"Editační rozhraní" (nyní "relief", změnit název)
"Přehled zapojených institucí"
"Statistika počtu titulů"
Ostatní soubory se nemají nabízet!!

2. je nutné vyřešit ty obrázky a soubory
3. potřebuju orámovat tabulky, takto jsou hrozné! Přidat "border" nefunguje. 
4. jak prolinkovat nebo na jiný soubor v témže adresáři? Momentálně vedou linky na starý web. (Stačí mi ukázka ve zdrojovém kódu)
5. číslované či odrážkové seznamy nefungují, nebo to je potřeba nějak upravit? (Obejdu se bez toho).

**Comment by lucka-pavlova** [comment]
Do 6.2.2018. Doladění obsahu a vzhledu s Albertem a Petrem.

**Comment by pkudela** [comment]
Nasadil jsem novou verzi -> http://sluzby.incad.cz/rdcz/home. Nyni se zobrazuje aktivni defaultni strana v levem menu. Co se tyce administracniho rozhrani jsou tyto zmeny:

-----
1. Menu - preklady tlacitek v navigaci v pravo
2. Menu - moznost volby v navigaci v pravo zneviditelnit stranku, tim padem zmizi z info sranky z leve navigace a zustane dostupna pouze v navigaci v administracnim rozhrani, cili neni smazana! - je oznacena a barevne potlacena viz. screenshot
![image](https://user-images.githubusercontent.com/16591052/35803633-c47a579c-0a74-11e8-8422-d4896e18ad93.png)
-----

**Comment by helena-oks** [comment]
Zneviditelnění stránky je výborné, i další nástroje. Přejmenovávat stránky pro uživatele asi nebudu moct sama? Vkládat stránku tedy můžu - vkopírováním obsahu. Ale jak přidávat obrázky a soubory?

**Comment by pkudela** [comment]
prosim odpovez, dik @albertoh

**Comment by albertoh** [comment]
Stranky (vlastne polozky v menu) maji nazev, ktere je neviditelny pro uzivatele. Nazev polozek pro uzivatele se nastavuje v tom editovatelnem boxu nad textem, ktery edituje. A to cesky a anglicky (podle nastaveni)

Obrazky take je mozne pridavat, pomoci tlacitka obrazek. Ten nahrava obrazek na server, a zaroven pridava do textu prislusny tag v poloze, odkud otevirame ten dialog.

Jeste existuje tlacitko "internal link", ktere slouzi pro odkazy v ramci rozhrani. Fragment je konkretni cast stranky (anchor)

To vsechno jsem mel v planu zdokumentovat, az jsem mel pocit, ze vsechno mam dodelane :)

**Comment by pkudela** [comment]
Nasadil jsem dalsi verzi. Sjednotil jsem vzhled/odsazeni info a help stranky a take jsem upravil levou navigaci u admin a info stranky. Byly tam zbytecne velke odsazeni vcetne velkych mezer mezi radky, celkove to pusobilo neprehledne nize muzete porovnat:

-------
Stara verze
![screen shot 2018-02-05 at 16 30 55](https://user-images.githubusercontent.com/16591052/35813479-003352b0-0a94-11e8-86e5-b953851dd398.png)

Nova verze
![image](https://user-images.githubusercontent.com/16591052/35813502-100200ba-0a94-11e8-99ef-fcffb5b72388.png)
-------
Je jeste ohledne editace neco, co byste potrebovala? Date nam prosim vedet behem zitrka az budete mit editaci stranek hotovou, abychom si do toho navzajem nezasahovali?

**Comment by helena-oks** [comment]
Abychom se nekřížili, pro dnešek tedy editaci končím, budu pokračovat ve čtvrtek, ale bude toho potřeba dodělat ještě dost . Zde shrnuji, co je a není vyřešeno - vycházím z prvního komentáře:
1.  dvousloupcové rozdělení a možnost úprav menu - OK (jen prosím smazat duplikovaný soubor ccnb, má zůstat pouze soubor data/ccnb)
2a.  obrázky - vkládají se dobře, ale zobrazí se jen jpg, gify nefungují - musím to předělat na jpg?
2b.  soubory - může se řešit vložením souboru na požádání, nemusím mít nástroj v editaci (pokud dostanu návod, jak vložit odkaz v kódu)
3.  tabulky - dvoubarevnými řádky celkem uspokojivě vyřešeno
4.  interní linky - nefungují na jiný soubor z nabídky, link na anchor ve vlastním souboru někdy ano, někdy ne - viz linky v souboru data (vč. odkazu ze zprávy na kontrolu výsledků)
5.  číslované seznamy fungují, odrážkové seznamy nefungují

**Comment by pkudela** [comment]
Za me:
-------
1. Tabulky upraveny na vzhled materialize, ktery v aplikaci pouzivame, jen se budou muset vycistit od zbytecnych stylu, to udelam ja, az budete vkladat novou tabulku, muzete pouzit tu z editace bez jakyhkoliv parametru, tabulka se pak vzhledove prizpusobi tomu, co je definovano v css
![image](https://user-images.githubusercontent.com/16591052/35859589-016a02b6-0b41-11e8-99a5-19a97d81ae30.png)
2. Zmensil jsem pismo u h5 a h4, podle noveho vzhledu prosim kdyz tak predelejte, semanticky by to melo byt tak, ze hlavni by vzdy mel byt vetsi headline, cili h4 a h5 pak doplnkovy. V idealnim pripade pouzivat v textu jen jeden treba h4 a ostatni zdurazneni resit dalsich textovych moznosti jako napr. strong, kurziva ...
3. Seznam jeste upravim aby fungoval a nahraju to na server
-------

**Comment by helena-oks** [comment]
Zvolila jsem H5 pro "nadnadpis" Infostránky schválně, protože důležité jakožto hlavní nadpis je až to pod tím. Jenom tučně by to asi nestačilo. U H5 se mi moc nelíbí, že je to nad čárou (=není jasné, k čemu to patří), ale dát jen tučně dál v textu je zase málo, jsou tam i tučné dílčí nadpisy (tučné je vůbec hodně málo výrazné - to je pouze konstatování). Jinak velikost OK. 
Jak použít tabulku z editace bez parametrů moc nevím - aby se zase nerozhodila, dalo mi dost práce odřádkovat správně in+URL kus po kusu...

**Comment by pkudela** [comment]
Nasazena nova verze:
------
1. zprovoznil jsem seznam, uz odrazky funguji -> http://sluzby.incad.cz/rdcz/info
2. co se tyce formatovani, tak tabulka by mela byt bez zbytecnych atributu a elementu, napr. odradkovani by se melo resit elementem <br/>, ale to je nyni nepodstatne, ted to nechme jak to je, nicemu to nevadi, vypada to pekne
3. U tabulky jsem musel na 2. sloupec s vyjimkou headeru aplikovat v css vlastnost word-break, jelikoz kvuli delce url pri zmenseni okna tabulka pretekala z hlavniho containeru a neprizpusobovala se zvolene sirce
4. Co se tyce h5 a h4 ok, chapu, cary muzeme uplne zrusit
5. Vas predchozi komentar, tam by melo fungovat vse krome vkladani souboru, tam se Alberto musi zamyslet jak to delat, kazdopadne to myslim neni zavisle na spusteni
6. Jinak jsem proklikal ceskou verzi a zkopiroval obsah do anglicke, aby to bylo totozne a zmizel tak u nekterych anglickych polozek pretekajici a rozbity obsah, nevim jak to mate s prekladem, u stare aplikace rdcz jste myslim anglickou verzi info stranek nemeli
------
Prosim tedy zitra o otestovani, abychom issue mohli zavrit. Dekuji

**Comment by helena-oks** [comment]
Ve středu nejsem v práci, tak můžu otestovat jen minimum.  Issue bych nezavírala, drobnosti nám zbydou i po zveřejnění. 
Body 1-3 OK, 4 dořešíme později (není fatální)
5 - Ještě mi nefungují vnitřní odkazy v rámci stránky (data - odkaz ze zpráva o výsledku - možná moje chyba)
6 - anglickou verzi to nemělo a asi mít nebude - info se týká přispívání a tudíž jen českých institucí. Možná časem přeložím přehled institucí a udělám jednu stručnou stránku a stručný help.  (Jestli lze v angl. verzi nedávat vůbec do menu Info a přidat to tam pozdějc, bylo by to lepší).

Pokud se to ve čtvrtek dá na produkci, ale nebude to veřejné (nebude prolinkována adresa), dodělám už všechno tam.

**Comment by albertoh** [comment]
Otestoval jsem vnitrni odkazy a mne fungujou. Pokud budete mit dal problemy prosim o popis jak to presne pouzivate.

Anglickou verzi ted by vyresil tim, ze bych presne kopiroval obsah cesky

**Comment by helena-oks** [comment]
Prověřila jsem fungování vnitřních odkazů a co nefunguje popisuju v příloze. 
[RD-Nefungující odkazy.docx](https://github.com/incad/registrdigitalizace/files/1719187/RD-Nefungujici.odkazy.docx)

**Comment by albertoh** [comment]
Ted by to melo byt stabilnejsi

**Comment by helena-oks** [comment]
Jestli to vydrží, vypadá to dobře.  Nefunguje už snad pouze odkaz z helpu na seznam institucí - z odkazu "kontaktní údaje".

**Comment by albertoh** [comment]
Opraveno

**Comment by helena-oks** [comment]
Funguje, ale ze seznamu institucí (z Info) se pak nemůžu vrátit o stránku zpět na Help ani přímo zavolat Help, ta stránka prostě zmizí a načte se zas až po F5.  Odkaz na tentýž seznam ze stránky Home se chová dobře.

**Comment by helena-oks** [comment]
Dobrý den,

Když už má zítra jít nový web naostro ven, mohl byste se ještě mrknout na ty dvě nedokončená issues? Snad to není příliš náročné… Děkuji!

Helena Dvořáková
