### ISSUE TITLE
nové vyhledávání - úpravy vyhledávacích funkcí

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#592]
Zde přenáším nesplněné požadavky ze starého vyhledávání (příslušná issue posléze uzavřu).

1/  je třeba vyhledávat i podle neplatného ččnb, a to jak ze základního okénka, tak i z tabulky polí .
Pokud by neplatné ččnb nešlo pro vyhledávání pod návěští "Číslo ČNB"  zařadit, pak musí být v tabulce polí návěští  "Číslo ČNB (plat.)". Ale byl by to nežádoucí stav, protože ččnb je pro RD klíčový údaj a leckdo neví, že má ve svém katalogu číslo neplatné.  Viz issue 327. Příklad: cnb001537131 (platné je cnb001024412).

2/ je třeba, aby se podle slov ve variantním názvu vyhledávalo jak v základním okénku, tak v tabulce polí z pole Název.  Viz issue 249. Příklad: Dukhovnyi mir studenchestva.

**Comment by helena-oks** [comment]
OK

**Comment by helena-oks** [comment]
Zdá se mi, že řazení podle relevance je jiné při vyhledávání základním a jiné při rozšířeném, resp. při rozšířeném vyhledávání se výsledky neřadí asi vůbec.
Příklad: "karel havlíček" v základním okénku - správně předřazeno, kde je text celý název; při hledání přes pole Název jsou dokonce mezi prvními výsledky záznamy, kde ani není přesné znění dotazu (jen lemmatizované formy) .

**Comment by albertoh** [comment]
Opraveno. 
Prosim o testovani

**Comment by helena-oks** [comment]
Není to zcela uspokojivé. Jak je to s přidělováním váhy pro řazení podle relevance v novém systému? Jde zařídit zhruba toto pořadí?
1. dotaz = název (přesně)
2. dotaz = název začíná (přesně)
3. dotaz = autor (první slovo)
4. dotaz = slovo/slova z názvu/autora (přesně)
5. lemmatizované formy dotazu v názvu kdekoli
6. dotaz = slovo v další údajích podle pořadí významnosti (variantní název, podnázev, vydavatel, místo vydání atd. - rozhodně NEBRAT z "překladu" sigly nebo druhu dokumentu!)
7. lemmatizované formy v dalších údajích  

Momentálně se výsledky na dotaz "Venkov" řadí jinak ve vyhledávání obecném a jinak z pole Název. Čistý název "Venkov" má jeden záznam na prvním místě, druhý na čtvrtém - proč?

**Comment by albertoh** [comment]
Vysledky z hlavniho boxu a podle pole nemusi byt stejna. Hlavni vyhledavaci okno posila dotaz do vice poli, a pridavanim hodnot do poli pokrocileho vyhledavani omezuje vysledky.

Nastaveni vah je nasledujici (vahy jsou multiplikativni):

title_full (presna shoda v nazvu) x10.0
autor_first (prvni slovo autora, vcetne diakritiky) x4.2
_text_nolemmas (vyskyt kdekoli vcetne diakritiky) x2.0
 title_nolemmas (vyzkyt v nazvu vcetne  diakritukou) x3.0 
varnazev (vyzkyt v varnazev, lemmatizovane ) x1.1 
title_prefix (nazev zacina) x2.0 
title (vyzkyt v nazvu, lemmatizovane ) x1.5  
autor (vyzkyt v autorech, lemmatizovane ) x1.2

Vahy lze prenastavit v konfiguracnim souboru bez buldovani aplikace

**Comment by helena-oks** [comment]
Tak bych prosila násobky přenastavit takto - uvádím v pořadí důležitosti, ! = změna:

title_full (presna shoda v nazvu) x10.0
! title_prefix (nazev zacina) x5.0  (předpokládám, že jde o celá nelemmatizovaná slova)
autor_first (prvni slovo autora, vcetne diakritiky) x4.2
title_nolemmas (vyskyt v nazvu vcetne diakritiky) x3.0
!! varnazev (vyskyt v varnazev, NElemmatizovat! ) x2.5
_text_nolemmas (vyskyt kdekoli vcetne diakritiky) x2.0
title (vyskyt v nazvu, lemmatizovane ) x1.5
autor (vyskyt v autorech, lemmatizovane ) x1.2

Předpokládám, že ty "překlady" druhu dokumentu (např. BK => kniha) nebo názvu knihovny (ze sigly nebo z vlastníka) už do vyhledávání nejdou vůbec! (Jinak se najde spousta irelevantního balastu).

**Comment by albertoh** [comment]
title_prefix neni totez co prvni slovo, ale prvni pismena textu v pole

Hodnoty vah menit bez testovani neni v poradku.
V dalsi fazi mohli bychom pridat do admin rozhrani kontroly pro nastaveni vah

**Comment by helena-oks** [comment]
Když to nebude řadit jinak hned se spuštěním nového webu, pak to samozřejmě nespěchá.

Možná by se změna nastavení vah dala udělat v testovací verzi, jestli ji nesmažete. Vybrala bych testy, aby byly výsledky co do počtu stejné, bylo by jen jiné řazení.  Testovat by pomohl pan Ljubka, kterému nevyhovující řazení dost komplikuje práci. (Jak v admin, to si neumím představit).

Dalo by se pak nastavit místo title_prefix to první slovo/první slova, tj. aby to zohledňovalo mezery mezi slovy?

**Comment by lucka-pavlova** [comment]
Můžem rozšířit administrativní rozhranní o možnosti nastavení vah. (cca 3 dny)

**Comment by pavelkocourek** [comment]
Jen ... pokud se to bude dělat, stačí zřejmě konfigurační soubor

**Comment by lucka-pavlova** [comment]
Zavírám, je nahrazeno issue #612.
