### ISSUE TITLE
nový web - chyba při zobrazování výsledků při 1 záznamu

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#593]
Je-li dotazem nalezen jen jeden záznam, někdy (ne vždy) se nezobrazí - je možno ho zobrazit až po kliknutí na 1. Viz obrázek
![rd-ch-vysledek](https://user-images.githubusercontent.com/13746425/35378246-6a3c07fa-01b2-11e8-975a-c57e417e5b68.jpg)

**Comment by albertoh** [comment]
Opraveno
