### ISSUE TITLE
RD.CZ: Nasazení nového hledání do ostrého provozu

### ISSUE THREAD

**Issue by lucka-pavlova** [incad/registrdigitalizace#594]
Úterý (6.2.2018) dokončení info stránek
Středa odsouhlasení celkového vzhledu 
Čtvrtek nasazení na PROD ( poslat   IP adresu)
Pátek přesměrování na nový server

**Comment by helena-oks** [comment]
Infostránky jsou nahrubo, protože ještě nejde vkládat interní linky (je jich tam dost). Když se to vyřeší, dodělám ve čtvrtek.

**Comment by helena-oks** [comment]
Na vnitřní IP jsem zkontrolovala, našla jsem jen drobnost - dole zůstalo (zřejmě z textu Info ke spolupráci) slovo "mezera". Už jsem avizovala nový web některým uživatelům - je možné to zveřejnit, tj. přesměrovat adresu  http://www.registrdigitalizace.cz/ na nový server co nejdříve?

**Comment by albertoh** [comment]
Mezera odstranena

**Comment by helena-oks** [comment]
V RD ke zveřejnění se ztratily v Info veškeré vložené obrázky - na testovací verzi jsou. (např. exportSKC,relief)

**Comment by albertoh** [comment]
Opraveno. Zrejme, se nekopirovaly spravne soubory.

**Comment by helena-oks** [comment]
Děkuju! Mohl byste ještě kouknout na issue 599, že bych něco dodělala v ENG, než to bude venku?

hedv

**Comment by helena-oks** [comment]
Před přepnutím pro uživatele zvenku (přesměrováním adresy na DNS) je nutné, aby nové vyhledávání bylo čerstvě aktualizované a aby  probíhaly pravidelné aktualizace!!

**Comment by albertoh** [comment]
Index se aktualizuje kazdou pul hodinu. Muzeme menit nastaveni, aby to bylo jeste casteji, pokud by to bylo nutne.
 1.03.2018 index ma 465552 predloh zaindexovane. posledni zmena v 9:00

Server registrdigitalizace.cz v tom samem okamziku ma 465011 predloh.

**Comment by helena-oks** [comment]
Nové vyhledávání počítá při sloučení podle ččnb jinak než staré, což je z jedné strany lepší, protože se to přibližuje počtu "titulů", ale zároveň to trochu mate. K této neavizované změně se měli zainteresovaní lidé vyjádřit (i zvenku se můžou divit, proč se ztratilo 40000 záznamů). Asi by tam mělo být v návěští jen "položek", protože ani při sloučení nejde vždy o tituly.
Nejvíc by se mi líbilo, kdyby se zobrazilo:  Nalezeno ... položek (po sloučení ...).

Úplně dobře však aktualizace neprobíhají, nevím proč. Konkrétně Pr000040549 jsem minulý týden smazala (přes "vyřazeno") a  v novém RD je, zatímco ve starém správně už není (šlo o duplicitu).  Další smazaný Pr000498146 se také zobrazuje, navíc se přes ččnb s tím druhým duplicitním nesloučil. Viz obr.
![rdakt1](https://user-images.githubusercontent.com/13746425/36835578-feccc23e-1d36-11e8-84ef-a8568cea2f97.jpg)
![rdakt2](https://user-images.githubusercontent.com/13746425/36835580-fefc62f0-1d36-11e8-8c0b-43b6d6fc4491.jpg)


(Naopak záznam pana Ljubky 1001289537 je správně vyhledatelný v novém RD a ve starém ho nalézt nelze).

Frekvence aktualizací je dostatečná.

**Comment by JanMeritus** [comment]
poprosim len pre poriadok, pokud sa vyskytnu dalsie vaznejsie fcne issues, tak idealne kazda do noveho vlakna

**Comment by albertoh** [comment]
Problem odstranenych predloh jsem opravil. Zaznam Pr000498146 zmizel.

Slouceni pres cCNB je uplne stejne jako ve starem. 
Bez slouceni ve starem: 465011 
Slouceno podle cCNB: 423077 
Rozdil ~40000

V novem (po reindexaci, a oprava smazani odstranene predlohy)
bez slouceni: 465384 
Slouceno: 423447

**Comment by albertoh** [comment]
Opravil jsem napis:
Nalezeno : 423447 položek

**Comment by helena-oks** [comment]
Díky, vypadá to dobře. Zmátlo mě to, že ve starém RD byl nahoře zobrazován celkový počet, což v novém není. Teď se zjistí "jakoby celkový počet" tím, že se odstraní filtry, a ten je díky sloučení o 40000 nižší. Kdyby byl někde vidět skutečný počet řádků, bylo by vše OK.

**Comment by lucka-pavlova** [comment]
Zdá se, že už nic nebrání nasazení do strého provozu. Můžeme nasadit?

**Comment by JanMeritus** [comment]
este poprosim odpoved na email co sa tyka garance prolinku a mozme jet nato

**Comment by albertoh** [comment]
pridal jsem pravidlo do VirtualHost, presmerovani / -> localhost:8080/rdcz

**Comment by helena-oks** [comment]
Akce proběhla sice se značným zpožděním, ale issue je možno uzavřít.
