### ISSUE TITLE
Upozornění, že jde o Beta verzi + kam hlásit bugy (mailto)

### ISSUE THREAD

**Issue by lucka-pavlova** [incad/registrdigitalizace#595]

**Comment by pkudela** [comment]
Posilam 2 verze, prosim vyberte si. Jak jsem psal Lucce tato informace je vetsinou svazana s logem, aby to uzivateli bylo na prvni pohled jasne. Jinak bych doporucoval dat do paticky webu odkaz s emailovou adresou (mailto), aby mel uzivatel kontakt stale po ruce a nemusel ho hledat na strance info, alespon do doby, nez to prestane byt beta verze. Souhlasite?

-------
![image](https://user-images.githubusercontent.com/16591052/35726948-da3a9fd0-0806-11e8-977f-b797f32fec42.png)

![image](https://user-images.githubusercontent.com/16591052/35727021-19b89d4c-0807-11e8-99fb-cc6ec5259df8.png)
-------

**Comment by pkudela** [comment]
Nasazena nova verze na testovaci server s druhou variantou -> http://sluzby.incad.cz/rdcz/home

**Comment by helena-oks** [comment]
Tuto vodorovnou variantu taky preferuju. Mailto považuju za nutné i po skončení betaverze. Nejvíc by se mi líbilo přidat Kontakt do menu, je to víc na ráně než v patičce. A taky bych kontakt přidala do bloku Informace ke spolupráci, kde text ještě upravím.

**Comment by pkudela** [comment]
Nasadil jsem novou verzi -> http://sluzby.incad.cz/rdcz/home Doplnil jsem kontakt do navigace. Nyni funguje jako klasicky odkaz (mailto), kde se otevre defaultni mailovy klient, nicmene bylo by mnohem lepsi, kdyby kontakt odkazoval na samostatnou stranku z formularem pro odeslani mailu z webu (coz ted k casovym monznostem neni realne), nebo na stranku kde bude emailova adresa zretelne uvedena, drive to bylo v horni casti stranky "info". Zkratka navigace by mela vzdy odkazovat na nejake misto.

**Comment by pkudela** [comment]
@helena-oks je mozno prosim zavrit?

**Comment by helena-oks** [comment]
Nezavírala bych, protože výhledově bychom Kontakt měli přesměrovat na formulář. Když se issue má znova otevřít, špatně se to hledá. Pro spuštění stav OK.

**Comment by pkudela** [comment]
Rozhodne bych to zavrel, jde o dalsi rozvoj aplikace a nazev tohoto issue zameru a funkcionalite neodpovida, pak by se to spatne dohledavalo. Zavru to a vytvorim novy issue, popisu to a priradim tomu labely - Aplikace - Nove vyhledavani + enhancement.
