### ISSUE TITLE
nový web - zastaralé a zavádějící info v "patičce"

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#601]
V šedé patičce jsou zcela zastaralé informace a myslím, že pokud něco chceme někde uvádět, můžu to v aktualizované podobě dát do Info - pokud dostanu text, protože technickým věcem nerozumím.

Byla bych pro to, aby tam byl jen název - anglicky je to "Digitization Registry"! + Partneři/Partners a loga. Nebo aspoň dočasně.

**Comment by pkudela** [comment]
To neni problem, s tim se ostatne i pocitalo, ze se text bude modifikovat, pripadne tam nemusi byt vubec. @pavelkocourek  Pavle, prosim dej mi vedet, jestli text ty nebo nekdo jiny upravi, pripadne jestli tam nebude vubec, v tom pripade bych tam nedaval ani titulek, protoze tim postrada smysl. Take prosim abys prosel ta loga, vcetne naseho a dal mi vedet, abych to behem pondeli stihnul upravit.

**Comment by pavelkocourek** [comment]
@pkudela info k logu mas v mailu
Návrh  nového textu jsem poslal na schválení TF

**Comment by pkudela** [comment]
OK, pockam na schvaleni textu.

**Comment by Foltom** [comment]
Ať to můžeme sledovat - posílám texty v Čj i Aj:

The Digitization Registry of the Czech Republic is a specialized national project, which is developed in the close cooperation of the National Library of Czech Republic, Moravian Library in Brno, Academy of Sciences Library and the Content Analytics Division of Accenture (formerly Incad). The project´s aim is to create national registry of digitized documents, which could help the librarians to avoid unwanted duplicities in the process of digitization and to enable sharing the digitization results across the Czech Republic. 

The system is built on RIII application framework (J2EE) and all the data are stored in Oracle relational database. Apache SOLR search engine is used for user data retrieval and browsing. All the user accesses are realized via web application. The Digitization Registry can widely communicate with different library systems used in the Czech libraries, including various digitization workflows, library OPACs or the Kramerius digital library.


Registr digitalizace je společnou aktivitou Národní knihovny České republiky, Knihovny Akademie věd, Moravské zemské knihovny a Content Analytics divize společnosti Accenture (dříve Incad). Jde o národní registr digitalizovaných dokumentů, který je napojený na digitalizační workflow jednotlivých institucí. Jeho základním posláním je zamezit nechtěným duplicitám ve výběru dokumentů určených pro digitalizaci a také přispět k efektivnímu sdílení výsledků různorodých digitalizačních aktivit, například těch podpořených dotačním mechanismem Ministerstva kultury ČR VISK 7. 
 
Systém je vystavěn na aplikačním frameworku RIII (J2EE). Data jsou následně ukládána do relační databáze Oracle. Pro zpřístupnění aktuální informace o stavu digitalizace koncovým uživatelům je použit vyhledávací nástroj Apache SOLR. Všechny uživatelské přístupy jsou realizovány prostřednictvím webové aplikace. Registr digitalizace aktivně komunikuje s dalšími systémy používanými v jednotlivých knihovnách – mimo již uvedených digitalizačních workflow je napojen na knihovní katalogy či digitální knihovnu Kramerius.

**Comment by pkudela** [comment]
Diky, upraveno, Alberto nasadi ve ctvrtek, az se vrati z dovolene.

**Comment by Foltom** [comment]
OK - pak můžete toto issue uzavřít. TF

**Comment by helena-oks** [comment]
V anglické verzi to opravené není! Je tam složitější rozdělení textu mezi dva bloky, které bych před spuštěním ráda viděla. A taky je tam pořád "digitalization registry", má být "digitization registry"!

**Comment by pkudela** [comment]
Omlouvam se, nebylo to zkopirovano na server, zkontrolujte anglickou verzi nyni.

**Comment by helena-oks** [comment]
Patička OK, ale zřejmě k vám nedorazil můj požadavek obsažený v mailu pana Foltýna 
týkající se bloku vpravo dole:

"Zároveň je potřeba, aby v anglické verzi nebyl český blok „Informace ke spolupráci“.  Pro zahraniční uživatele postrádá smysl. Mohlo by se tam dát „Basic information“  a do obsahu třeba toto (ale radši bych, kdyby to někdo napsal anglicky líp):

Digitization registry is a national registry of digitized documents. Its main aim is to avoid unwanted duplicate digitization. It serves also as the central access point to digitzed documents. To know more about the digitizing institutions, see the list of participating institutions  (s odkazem).

Pozor, je velmi žádoucí, aby se někde vyskytl anglický název Digitization registry, protože v univerzálním logu je český název."

Pak už to snad bude vše :)

**Comment by albertoh** [comment]
Zmeneno
