### ISSUE TITLE
Digitální knihovny a sklizená URL + sklízení NDK v NK

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#603]
Otvírám zvláštní issue pro zařazování připojených záznamů ze sklizní do DK pro nový web - tento problém v issue 583 vyřešen nebyl:

"DK Národní knihovny - nová digitalizace má jen malý počet záznamů. Znamená to, že se započítává jen URL, které je v předloze, a ne URL ze sklizně K4 připojené z tabulky digitálních dokumentů? Pak je ovšem počet hodně zkreslený a ani filtr nefunguje, jak má."

Nefunguje správně ani po částečné nápravě! (Jde tedy o chybu funkcionality, která zkreslí výsledky filtrů na webu - nikoliv o požadavek na rozvoj).

Zjistila jsem, že do této DK jsou nyní zařazeny pouze záznamy vlastníka BOA001 (které obsahují v předloze v poli URL/URLTITUL takové UUID, které se nachází i v dig.dokumentu sklizeném z DK NK) + nějaké záznamy ABA001, které mají obsazené URL/URLTITUL v předloze.  Podrobně s ukázkami v příloze.

[digknihovnyNDK.docx](https://github.com/incad/registrdigitalizace/files/1758234/digknihovnyNDK.docx)

**Comment by JanMeritus** [comment]
taky som za to aby sa to vyriesilo pred nasazenim. Pani @helena-oks ?

**Comment by helena-oks** [comment]
I já bych to preferovala, ale pokud to neznamená dlouhý odklad. Už nový web slibujeme hodně dlouho.

**Comment by albertoh** [comment]
Reindexoval jsem znovu.
Problem byl pripojeni pres dig objekt, ne urltit, ani urltitnk. 
Pocet ted je 145220. Je to realni?

**Comment by helena-oks** [comment]
Zdá se mi to odpovídající, někde možná došlo k nesprávnému spojení, každopádně je to blízko realitě. Ještě jedna drobnost - aby se pod "Digitální dokument" zobrazily i URL z předloh, která jsou schovaná pod šipkou u předlohy (s výjimkou periodik). Když chce někdo vidět dig.dok., tak tam rovnou přepne z předlohy. Příklad 1 z přílohy - Od moře k moři - má mít dole vidět dvě URL.

**Comment by albertoh** [comment]
Vratil jsem to do puvodniho. Tj, v predloze je url, dole url+urltit+urltitnk

**Comment by helena-oks** [comment]
U knih je to teď v pořádku.  Ale bylo by fajn, kdyby šlo u druhu dokumentu SE (=periodikum) potlačit zobrazování url (z předlohy) dole, jak jsem chtěla v jiném issue. Když se podíváte na digitální dokumenty u záznamu  cnb001302356, je to strašně nepřehledné. Jestli je to problém, nechme to takto, není to tak častá situace.

**Comment by albertoh** [comment]
Schovavano pro SE

**Comment by helena-oks** [comment]
Bezva! Tak snad to máme vyřešené - než zas něco objevím ;-)
Omlouvám se za vytrvalé obtěžování, ale i když nejsem perfecionista, nějak na mě zrovna ty podstatné chybky přímo vyskakují...

**Comment by lucka-pavlova** [comment]
Můžeme tedy issue zavřít?
