### ISSUE TITLE
Nesrovnalost v indexovaných datech

### ISSUE THREAD

**Issue by Foltom** [incad/registrdigitalizace#604]
V rámci práce s Registrem digitalizace objevil Dr. Ljubka několik nesrovnalostí mezi daty obsaženými ve webovém rozhraní Registru digitalizace a vnitřním Reliefu (viz příklady v přílohách). 

![defense_rd](https://user-images.githubusercontent.com/16835471/36898510-6c32ac64-1e1b-11e8-9918-f607cb124842.jpg)
![defense_relief](https://user-images.githubusercontent.com/16835471/36898511-6c530df6-1e1b-11e8-940c-3bc1ce3548b1.jpg)
![pr000502720_rd](https://user-images.githubusercontent.com/16835471/36898512-6c72ea0e-1e1b-11e8-82b7-a7e5bff546e9.jpg)
![pr000502720_relief](https://user-images.githubusercontent.com/16835471/36898513-6c907664-1e1b-11e8-80ae-eab525d9f079.jpg)

Cituji: "Narazil jsem na další (podotýkám, že ve starém RD), které nejsou dohledatelné přes rozhraní RD, ačkoliv jak je zřejmé z obrázku, v Reliefu jsou. Nejde o poslední data, ale o data, která by měla být v RD již řadu let. Jde totiž o Norské fondy. Tyto jsou konkrétně z roku 2009. Prosím o urychlené přeindexování, aby bylo možné s aplikací pracovat. V příloze (pro pořádek) zasílám prtscny".

Jde o to, abychom při překlopení Registru o tato data nepřišli. Rozdíly se objevují i po poslední reindexaci provedené včera A. Hernandezem. Pokud jste schopni garantovat, že při překlopení nedojde ke ztrátám dat, ani k chybám v konzistenci, tak dejte vědět. Jinak prosím o zhodnocení, proč se Registr v těchto případech chová tak, jak ukazují print screeny. Třeba je tam jiný důvod.

Děkuji. 

TF

**Comment by albertoh** [comment]
Vcera jsem reindexoval jen index pro nove rozhrani. Stavajici server s Fastem funguje dal sam od sebe, bez mych zasahu.
 Myslim si, ze do noveho indexu se dostavaji vsechny predlohy, aspon ja nevidim zadnou chybu.

V novem rozhrani:
Podle car. kod =1000356860 vysledek 3 zaznamy:

 - Défense des colonies. II., Incompabilité entre le systême des plis et la réalité des faits matériels
 - Défense des colonies. I., Groupe probatoire comprenant La colonie Haidinger, La colonie Krejči et La coulée Krejči
 - Défense des colonies. III., Étude générale sur nos étages G - H avec application spéciale aux environs de Hlubočep, près Prague

Pokud zapnu test duplicity, z Alephu najdeme nazev "Défense des colonies.", a rohrani vrati 5 zaznamu:

  - Défense des colonies. IV.
  - Défense des colonies. II., Incompabilité entre le systême des plis et la réalité des faits matériels
  - Défense des colonies. I., Groupe probatoire comprenant La colonie Haidinger, La colonie Krejči et La coulée Krejči
  - Défense des colonies. III., Étude générale sur nos étages G - H avec application spéciale aux environs de Hlubočep, près Prague
  - Défense des colonies. V., Apparition et répparition en Angleterre et en Ecosse des espèces coloniales siluriennes de la Bohême : d'après les documents anglais les plus authentiques et les plus récents

Hledani podle Číslo RDCZ = Pr000502720
vrati jeden zaznam: 
"Historický lexikon obcí České republiky 1869-2005"

Preklopenim na nove rozhrani nemuzeme prijit o zedne data, ta jsou v db. Ba naopak, najdeme ty zaznamy, ktere z nejakeho duvodu nejsou dohledatelne v Fastu.
Ja bych poprosil testovat nove rozhrani, a ne to stare. Pokud ovsem nechceme, abych stravil den zkoumanim stareho serveru, a logu ve Fastu

**Comment by lucka-pavlova** [comment]
Můžeme toto issue, které se týká starého rozhranní, zavřít?
A případně otevřít nové issue, pokud se podobný problém objeví v novém hledání.
Děkuji!

**Comment by Foltom** [comment]
Zavírám. TF
