### ISSUE TITLE
nový web - zobrazení bibliografických údajů

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#606]
Našla jsem ještě 2 odchylky v zobrazení oproti starému webu - prosím o nápravu:

1/ ztratil se podnázev - zobrazoval se menšími písmeny pod názvem, bez návěští (případně to návěští Podnázev mít může, je-li to jednodušší nebo hezčí).
Příklad: Historie povodní v Praze v grafice, malbě a fotografii

2/ při stejném ččnb se to slučuje jinak, dřív se to slučovalo v případě, že tam byla ABA001, pod její záznam. (Jiné knihovny ho mívají méně úplný, např. tam není název části nebo podnázev).
Příklad:  cnb001091562 a další svazky Encyklopedie řádů

**Comment by albertoh** [comment]
Opraveno

**Comment by helena-oks** [comment]
Díky - i za rychlost :)
