### ISSUE TITLE
Přesun WS pro workflow na nový server

### ISSUE THREAD

**Issue by lucka-pavlova** [incad/registrdigitalizace#607]
Spolu s vyhledáváním se stěhuje na nový server i WS pro workflow.  
Před změnou DNS je potřeba ověiřit:
Jestli workflow odkazuje na WS pomocí  IP adresy neo DNS
Jestli je “nová” WS otestovaná a nasměrovaná na produkční DB

**Comment by helena-oks** [comment]
Zde je zpráva o výsledcích testování WS v NK a následný požadavek na úpravu textu v "Informace o spolupráci" (původní text prosím schovat, aby se posléze vrátil):
----
Další testy má cenu dělat (a sledovat datový traffic) až po překlopení. Na základě výše uvedeného jsme se s kolegy dohodli, že mimo informace o bety verzi v záhlaví prozatím nahradíme v bloku „Informace o spolupráci“ část „Využívejte kontrolu v RD na ochranu před zbytečnou duplicitní digitalizací! Můžete vyhledávat i v Dalších zdrojích ze zahraničních digitalizací.“ následnou informací:

„S ohledem na nasazení nové beta verze Registru digitalizace může docházet k nestandardnímu chování systému. V případě zjištění jakýchkoli nedostatků prosíme o jejich ohlášení prostřednictvím odkazu https://github.com/incad/registrdigitalizace/issues.“ 
----

**Comment by lucka-pavlova** [comment]
Místo "tohoto odkazu" bych napsala  "GitHub Issues". 
Alberto má tenhle týden dovolenou, takze novou verzi nasadí asi až v týdnu od 19.3.2018.

**Comment by pkudela** [comment]
hotovo, commitnuto, pro nahled zatim nasazeno jen na sluzbach -> http://sluzby.incad.cz/rdcz/home

**Comment by helena-oks** [comment]
OK. Ale protože se to stejně celé nezobrazí, preferovala bych zkrátit víc. Třeba:

Protože jde o betaverzi, může docházet  k nestandardnímu chování systému. Případné závady prosíme nahlásit prostřednictvím GitHub Issues. 

Ale na znění nijak netrvám.

**Comment by pkudela** [comment]
pardon, testovaci server je pristupny z venku pod touto url -> http://194.108.215.248/rdcz/home

**Comment by pkudela** [comment]
ok, hotovo, text vymenen -> http://194.108.215.248/rdcz/home

**Comment by albertoh** [comment]
Text zmenem. Zaviram
