### ISSUE TITLE
info a help v anglické verzi se ztratily

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#608]
Přeložila jsem všechny potřebné soubory v ENG, do nepotřebných jsem dala "not available", a teď je tam znovu stav před přeložením, tj. český! Doufám, že se soubory neztratily, dalo mi to hodně práce.

**Comment by albertoh** [comment]
Jak jste to prelozila?
V logach nevidim zadny pokus o ukladani textu, ani zadnou chybu

**Comment by albertoh** [comment]
Uz vidim, 
je to na backendovym serveru, 10.1.20.48/rdcz
Ostry server je jiny. Staci kopirovat soubory

**Comment by helena-oks** [comment]
Já  tam dělala v mezičase, než se to zveřejnilo, možná i další změny, v české verzi. Předpokládala jsem, že to zveřejněné bude  fyzicky totéž, jen se tomu dá vnější adresa a předělá se dns. Je možné to prověřit?

**Comment by helena-oks** [comment]
A dnes jsem pro změnu sahala do souborů info na nové veřejné verzi...

**Comment by helena-oks** [comment]
Překopírovala jsem ENG soubory. Je možné z logů zjistit, jestli bylo něco editováno v CZE zhruba ve stejné době?
