### ISSUE TITLE
Založení svazku ve WF NDK - Dokument nebyl zaevidován v RD

### ISSUE THREAD

**Issue by zdenekhruska** [incad/registrdigitalizace#610]
Dobrý den, 
v RD byl ze stavu "Dokončeno" vrácen svazek do stavu "Ve zpracování". Nicméně v digitalizačním workflow NDK nejde svazek založit, chybová hláška je tato: 
Chyba validace dat. Důvod: Dokument nebyl zaevidován v registru digitalizace.

Nové svazky ve workflow NDK zakládat jdou, stejně jako je výše zmíněný svazek ve webovém rozhraní RD bez problémů dohledatelný. 

čárový kód svazku: 2610272322  
číslo RDCZ: Pr000342568

**Comment by MKortus** [comment]
Dobrý den,
bohužel v logách ani na jednom ze serverů není žádná informace o pokusu nalézt požadovaný záznam. Na původním serveru jsou zaznamenána volání WS, ale již ne konkrétní hodnoty (parametry) volání. Na novém se momentálně logují pouze chyby.

Na serveru 195.113.132.118 (nový server pro hledání) jsou zaznamenány výpadky spojení z následujících dní a časů, Je zde zaznamenán výpadek spojení, podle mého když se ws pokoušela předat informace zpět klientovi, který požadoval činnost, kdy, pravděpodobně pro timeout, bylo spojení již ukončeno, takže nebylo kam vrátit výsledek.
19-Mar-2018 10:11, 11:45, 14:24
20-Mar-2018 08:38, 10:51
23-Mar-2018 12:44

Na serveru: 195.113.134.12 (původní server pro hledání) jsou zaznamenány následující výpadky spojení. Jedná se o spojení na databázi, kdy bylo spojení ukončeno, pravděpodobně problémem na síti.
Mar 19, 2018 10:56
Mar 20, 2018 5:30, 11:15
Mar 21, 2018 2:41, 6:59
Mar 22, 2018 7:21, 8:17
Mar 23, 2018 7:30, 7:33

Je podivné, že dotazy chodí na oba servery. Bylo nám řečeno že se pro volání WS z workflow používá adresa s názvem serveru (například: http://www.registrdigitalizace.cz/soapservices/DigitizationRegistryService), tato adresa již ale odkazuje na nový server a i proto se WS nasazovala na nový server, jaká aplikace se tedy dotazuje původního serveru? Na původní server se hlásí "logica-wsclient", na novém serveru bohužel v logu není uložena informace kdo službu volá.

V Reliefu je záznam uložen s příznakem "ve zpracování". takže z toho pohledu by vše mělo být v pořádku.

**Comment by JanMeritus** [comment]
Dobry den, mozem sa opytat preco na novom servri sa loguju pouze chyby a chyba aj identifikacia volajucich uzivatelov?

**Comment by zdenekhruska** [comment]
Dobrý den, 
issue bylo paní @lucka-pavlova zavřeno, ale problém rozhodně vyřešen není - stále nám svazek nejde založit (a není jediný - do zpracování se vracelo svazků několik a ani jeden z nich nejde založit ve WF NDK).
