### ISSUE TITLE
Sloučit výsledky vyhledávání podle názvu

### ISSUE THREAD

**Issue by indrakm** [incad/registrdigitalizace#613]
Možnost sloučení výsledků vyhledávání podle názvu viz obr
![1](https://user-images.githubusercontent.com/12444931/38247573-1afdfe40-3746-11e8-8a57-4abc008878a7.JPG)

_Toto issue je spoleným požadavkem přípravy NK ČR i MZK ze schůzky 26.3.2018__

**Comment by Foltom** [comment]
Zjistit náročnost. Podle toho se určí priorita. H. Dvořáková vysvětlí jiné možnosti řazení na krajských digitalizacích.
