### ISSUE TITLE
divný výsledek vyhledávání (nový web)

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#621]
Na dotaz "čína a mongolsko" se nenašel titul s tímto názvem, který v reliefu je. Viz obr. Proč?

Nabídla se spousta záznamů, některé naprosto nerelevantní (na dalších stránkách). Varování (žluté oznámení o neúspěchu) se objevilo až zcela dole po rolování. Mělo by být nahoře.  Při listování se nabízely divně šipky pro posun - bez označení čísel stránek.

Po profiltrování na druh dokumentu Mapy jsou již na první stránce zcela nerelevantní záznamy. Viz obr. proč se našly?

![rd-cina1](https://user-images.githubusercontent.com/13746425/39189423-817c1692-47d2-11e8-8b06-a68373ea3e4a.jpg)
![rd-cina2](https://user-images.githubusercontent.com/13746425/39189424-81997656-47d2-11e8-93de-6045fa5b9096.jpg)

Bohužel stále nemůžu dávat labely...

**Comment by albertoh** [comment]
Danni titul ma stav = interni.
Neindexujeme  zaznamy v tomto stavu

Opravim zlutou hlasku, aby byla na hore

**Comment by albertoh** [comment]
Hlaska uz je na prvnim miste

**Comment by helena-oks** [comment]
Neindexování interního záznamu je v pořádku, za posun hlášky děkuji. Ty nerelevantní záznamy byly zřejmě kvůli nalezené spojce "a" jakožto jednomu ze zadaných slov, což sice není optimální, ale mohlo mě to napadnout.
