### ISSUE TITLE
přeindexovat vyhledávání - špatné počty záznamů u ABA001-DK a BOA001-DK

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#689]
Záznamy se opět špatně přiřazují k digitálním knihovnám. Opět nefunguje to, co jsem požadovala napravit v issue #679. (Issue jsem znovu otevřela a v commentu popsala situaci).

Bude třeba přeindexovávat periodicky???

**Comment by albertoh** [comment]
Nemelo by byt potreba. Zkoumam proc to mizi.

**Comment by albertoh** [comment]
Chyba byla zpusobena nastaveni letniho casu na serveru a indexu.
Ted by to melo reindexovat automaticky spravne. 
Index je nyni aktualizovan.

**Comment by helena-oks** [comment]
Počty záznamů zhruba odpovídají, takže issue by se mohlo uzavřít. Ale objevila jsem chybu, o níž nemůžu říct, jestli před indexováním byla nebo nebyla:

Neplatí, že přidělení druhé DK se týká pouze záznamů, které mají kód financování iop nebo ndk-u! 

V BOA001-DK je cca 8.000 záznamů, které mají vlastníka ABA001 a financování NorskeFondy - ty mají být pouze v ABA001-DK. Otevřela jsem proto  #669.

**Comment by albertoh** [comment]
Takze podminka pro propojeny je:
  1.- pokud zaznam ma financovano=iop nebo financovano=iop-ndku a digknihovna=ABA001-DK pridam digknihovna BOA001-DK
  2.- pokud zaznam ma financovano=iop nebo financovano=iop-ndku a digknihovna=BOA001-DK pridam digknihovna ABA001-DK

Je to tak?

**Comment by helena-oks** [comment]
Základní požadavek přesněji:
1/ je-li sigla1=ABA001 a  (financovano=iop nebo financovano=iop-ndku), pak k uuid ze sklizně vyrobit 2 URL - jedno s prefixem pro ABA001-DK a druhé pro BOA001-DK
2/ je-li sigla1=BOA001 a  (financovano=iop nebo financovano=iop-ndku), pak k uuid ze sklizně vyrobit 2 URL - jedno s prefixem pro ABA001-DK a druhé pro BOA001-DK


Pokud by to šlo, tak navíc toto pro případy, kdy se uuid nenapojilo na předlohu  a máme URL v datech předlohy:

3/je-li sigla1=ABA001 a  (financovano=iop nebo financovano=iop-ndku) a je (URL nebo URLtitul) s prefixem pro ABA001-DK (jiný prefix ne!), pak vyrobit další URL, kde bude před uuid prefix pro BOA001-DK
4/je-li sigla1=BOA001 a  (financovano=iop nebo financovano=iop-ndku) a je (URL nebo URLtitul) s prefixem pro BOA001-DK (jiný prefix ne!), pak vyrobit další URL, kde bude před uuid prefix pro ABA001-DK

**Comment by albertoh** [comment]
Reindexovano podle 1/ a 2/.

**Comment by helena-oks** [comment]
Započítávání do DK je asi v pořádku, ale linky do MZK se generují i v případech, kdy kvůli financování záznam od ABA001 do BOA001-DK nepatří. Dokument v ukázce je dig. z Norských fondů (proto je i ve staré digitalizaci). Je v ABA001-DK (sklizeno a připojeno uuid), není v BOA001-DK (a nemá tam být) – ale vytvořil se z uuid SLEPÝ link do mzk! 
![screta](https://user-images.githubusercontent.com/13746425/62942645-028f2800-bdd9-11e9-9763-7b520435715f.jpg)

**Comment by albertoh** [comment]
Opraveno.

**Comment by helena-oks** [comment]
Díky, vypadá to dobře! Zkusíte obdobně nastavit též 3 a 4?

**Comment by helena-oks** [comment]
Příklady, kde by měla být přidána DK a kde by měly být 2 URL:
- Akvárium a terárium (přidat odkaz a zařadit do ABA001-DK)
- Aleš a Jirásek (dtto)
- Chřiby záhadné a mytické (přidat odkaz a zařadit do BOA001-DK)
- Česká hospodyně (dtto)

**Comment by albertoh** [comment]
3 a 4 implementovano. Otestujte, prosim.

**Comment by helena-oks** [comment]
Vypadá to dobře, co do počtu i konkrétní odkazy. Jen se nám možná takto zpracovávají i záznamy, co financování nemají nebo mají financování "vlastní", ale to je možná způsobeno špatnými daty, nebo že už tam odkazy do obou DK byly. Nejdřív to prozkoumám, zatím nastavení neměnit.

**Comment by helena-oks** [comment]
Děkuji, teď se to chová zcela podle podle požadavků, odchylky způsobují nepříliš korektní data.
