### ISSUE TITLE
Předání popisu infrastruktury a projektu IT NKP

### ISSUE THREAD

**Issue by lucka-pavlova** [incad/registrdigitalizace#690]

**Comment by lucka-pavlova** [comment]
Servery - přístupy - SSH klíče -tabulka serverů a nainstalovaných komponent
Databáze
Zálohování

**Comment by JanMeritus** [comment]
Dobry den, pozeram ze povznikali dalsie issues, nicmenej pre pehladnosti, pridam to sem cele, zvysok dohodnutou cestou.

- [ ] 1. Pristupy 
  - [ ] do vsech casti reseni 
- [ ] 2. Kompletni popis prvku s ohledem na deleni FE, BE, inteni, externi
  - [ ] Infrastruktura, OS, middlewaru 
  - [ ] rozlozeni aplikacni vrstvy a roli jednotlivych elementu
  - [ ] tok dat, ulohy SOAP atd
  - [ ] Popis metodiky zaloh konfiguraci, casti ci celych programu, kompletnich prostredi
  - [ ] Rebuild a rollback systemu 
  - [ ] Popis jednotlivych dulezitych konfiguraci pro provoz systemu
- [ ] 3. Popis vyvojoveho, testovaci a produkcniho prostredi
  - [ ] Popis administracnich vrstev
  - [ ] Popis uzivatelskych roli
- [ ] 4. Datova vrstva - popis
  - [ ] Index a jeho schema 
  - [ ] DB 
    - [ ] popis dat
    - [ ] popis metadat
  - [ ] kontrola integrity dat
  - [ ] validace unikatnosti prvku a forem dle ciselniku
  - [ ] nastaveni ciselniku pro app, prip jejich prizpusobeni novym uziv pozadavkum 
  - [ ] kontrola duplicit
  - [ ] hromadne importy
  - [ ] hromadne opravy
  - [ ] index a jeho upravy
  - [ ] reindex
  - [ ] Archivace, zalohovani a rebuild
- [ ] 5. Predani dokumentace - dohodou
  - [ ] RDCZ, Administracni
  - [ ] SOAP, Administracni
  - [ ] RELIEF III, Administracni
  - [ ] RDZCUniImporter, Administracni
  - [ ] DB, Administracni
  - [ ] RDCZ, Uzivatelska (ak je)
  - [ ] SOAP Klient, Uzivatelska (ak je)
  - [ ] RELIEF III, Uzivatelska (ak je)
  - [ ] RDZCUniImporter, Uzivatelska (ak je)
- [ ] 6. Prevedeni kompletnich projektu vcetne zdrojoveho kodu, wiki a issues do repository NLCR, citlive prvky dohodou
  - [ ] FE
  - [ ] BE
  - [ ] konfigurace, skripty

**Comment by JanMeritus** [comment]
K predaniu dokumentacie nedoslo - predcasne vypovedanie zmluvy. Navyse na zaklade emailu od Lucky P. zmienujucich ze A. Hernandez a L. Sykora z Accenture odisli do fi Innovatica tiket uzatvaram ako nesplnitelny. NK poptava po svojom dodavatelovi.
