### ISSUE TITLE
Nefunkcnost FE RD

### ISSUE THREAD

**Issue by JanMeritus** [incad/registrdigitalizace#694]
Dobry den, uz vyse hodiny nebezi FE RD. SOAP servica zda sa ze bezi. Prosim o kontrolu, napravu a pripravu "obvykleho reseni."

V prilohe pridavam screen:
<img width="1319" alt="Screenshot 2019-08-15 at 17 57 04" src="https://user-images.githubusercontent.com/25201690/63107992-32c7f980-bf86-11e9-94a4-823e26e241b4.png">

**Comment by albertoh** [comment]
Opraveno. Moje chyba pri poslednich upravach
