### ISSUE TITLE
Špatná odezva RD

### ISSUE THREAD

**Issue by xb1** [incad/registrdigitalizace#696]
Při Vyřazení z digitalizace končí proces v chybě

... com.logica.ndk.tm.utilities.ExceptionMessage 	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:146) 	at $Proxy41.setRecordState(Unknown Source) 	at com.logica.ndk.tm.utilities.integration.rd.RDSetRecordStateImpl.setRecordState(RDS ...

V logu je toto:
2019.08.19 18:46:09,043  WARN [ActiveMQ Session Task-31045] org.apache.cxf.phase.PhaseInterceptorChain - Interceptor for {http://registrdigitalizace.cz/soapservices}DigitizationRegistryService#{http://registrdigitalizace.cz/soapservices}setRecordState has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Response was of unexpected text/html ContentType.  Incoming portion of HTML stream: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/soapservices/DigitizationRegistryService">POST&nbsp;/soapservices/DigitizationRegistryService</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

Otočení nic neřeší.
Jde o http://hvwffe01/safe/PersistentObjectAction.do?id=32314618&pageType=tabsig&m=prehlednkcr

**Comment by Ewusshka** [comment]
Issue sa moze uzavriet. Po opakovanom otoceni zvazku, akcia sa ukoncila zdarne.
