### ISSUE TITLE
hromadná oprava URL a URLTITUL

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#697]
Prosím opravit URL a URLTITUL u všech záznamů ABG001 (sigla1) , které v těchto polích obsahují "uuid" a pole nezačíná "https:" , následujícím způsobem:

Výsledné URL nebo URLTITUL musí vždy vypadat takto:
https://digitalniknihovna.mlp.cz/uuid: ..... , tj. zůstává vše od uuid:, ale předchozí řetězec (jakýkoli) se musí nahradit řetězcem "https://digitalniknihovna.mlp.cz/"
Dále je třeba vyplnit datum akce do pole edidate a do pole edidateurl. 

(Původní, nyní nefunční URL/URLTITUL vypadaly např. takto:
1/ http://digitalniknihovna.mlp.cz/mlp/view/uuid....
2/ http://digitalniknihovna.mlp.cz/mlp/periodical/uuid....)

**Comment by dgreslik** [comment]
Je potreba sa dohodnúť s predchádzajúcim dodávateľom supportu ohľadom prístupu do databázy a postupu riešenia

**Comment by helena-oks** [comment]
děkuji, vše v pořádku.
