### ISSUE TITLE
Zařazování záznamů pod digitální knihovnu

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#698]
Záznamy se špatně zařazují pod digitální knihovny, které mají shodný začátek URL "www.digitalniknihovna.cz". Ten začátek je totiž společný pro různé DK, jen doména nestačí. Je potřeba, aby se to zařazovalo **podle celého řetězce, co je uložen v tabulce digknihovna**:

select zkratka,URLdigknihovny,poznweb from digknihovna where instr(URLdigknihovny,'digitalniknihovna')>0
order by zkratka; 

ABD024-DK	http://www.digitalniknihovna.cz/vsup
BOA001-DK	http://www.digitalniknihovna.cz/mzk/
ZLG001-DK	http://www.digitalniknihovna.cz/kfbz
ABG001-DK	http://digitalniknihovna.mlp.cz/

**Comment by JanMeritus** [comment]
len pre doplnenie. 

V pripade SSL protokolu?
U ABG001-DK neplati vyssia typologia retazcov?

**Comment by helena-oks** [comment]
ABG001-DK je OK, dostala se do seznamu jen proto, že hledání bylo na řetězec "digitalniknihovna". Upravit je třeba jen ty ostatní. S čím pracuje zařazování pod DK v uživatelském webu nevím.

**Comment by helena-oks** [comment]
Přeneseno na interní git - issue5
