### ISSUE TITLE
nefunkční importy

### ISSUE THREAD

**Issue by indrakm** [incad/registrdigitalizace#701]
Od včerejška nechodím importní hlášení. Asi zase došlo . Děkuji za rychle řešení

**Comment by JanMeritus** [comment]
zadane na dodavatela

<img width="917" alt="Screenshot 2019-12-17 at 07 32 54" src="https://user-images.githubusercontent.com/25201690/70970819-af3b2800-209f-11ea-97f3-aee6773c58e4.png">

**Comment by dgreslik** [comment]
Je potreba sa dohodnúť s predchádzajúcim dodávateľom supportu, kvôli prístupu do databázy a postupe riešenia

**Comment by helena-oks** [comment]
Importy stále neprobíhají !!! Před "vánočními prázdninami" bylo několik normálních pracovních dní, kdy mělo dojít k nápravě, a žádná reakce!

Soubor, který jsem poslala na ftp 17.12.  (Dec 17 13:02 aba001_R0_rdopr_9.xml) již tam není a doufám, že se neztratil.

**Comment by indrakm** [comment]
@helena-oks potvrzuji, 16 dni bez reakce. Potrebujeme to urgentne vyresit.

**Comment by indrakm** [comment]
@JanMeritus prosim alespon nejaky komentar k tomu v jakem je to stavu

**Comment by helena-oks** [comment]
Nic nového se neimportuje od 13.12. Viz http://195.113.134.53:8107/nkp/digital/plaant?action=desk&deskName=cz.incad.rd.Importy. Poslední import proběhl normálně. Kam se poděly soubory, které se na ftp dostaly a už tam nejsou, nevím. Nevíme tudíž ani ve kterém stádiu importní program havaroval a proč se znovu nespustil. Takhle ta spolupráce se supportem fungovat nemůže! Chodí vůbec někomu z CGI zprávy z těchto issues?

**Comment by JanMeritus** [comment]
@helena-oks dodavatel o tom vie a je dohoda ze sleduje aj tieto issues. @indrakm  20.12. som posielal email na Vas vsetkych, caka sa na Vasu sucinnost.

**Comment by helena-oks** [comment]
Stav k 6.1. je stále neuspokojivý!

3.1. došlo ke zpracování souborů z ftp z adresáře cba001r, které dosud importní program z neznámého důvodu "nevybíral" - viz Issue 665.  Šlo o větší množství souborů a větší množství záznamů, podle logů importy proběhly dobře, podle kontroly výsledků nikoli - **došlo ke zdvojení některých záznamů se stejným identifikátorem (001)**!  Nemůžu vyloučit, že v importním souboru byly tyto záznamy dvakrát, ale importní program byl nastaven tak, aby prováděl kontrolu a záznam se stejným identifikátorem jako nový neimportoval.

**Od zpracování CBA001 již další importy neprobíhají**, ačkoli bylo na ftp od 16.12. posláno na ftp vícero souborů (určitě ABA001 a BOA001), které na ftp už nejsou a lze těžko zjistit, co tam bylo - mohly tam být i soubory od jiných knihoven. **Kde jsou soubory stažené z ftp?** 

Obávám se, že došlo k nějaké **nežádoucí úpravě importního programu** (vedlejší efekty?). Nebo 3.1. běžela **jiná verze importního programu**?  Prosím o sdělení, jaké akce proběhly 3.1. ze strany supportu. 

@JanMeritus - je opravdu nutné s tím něco udělat!

**Comment by JanMeritus** [comment]
@helena-oks zabyvame sa tym prioritne

**Comment by luckajirku** [comment]
> ačkoli bylo na ftp od 16.12. posláno na ftp vícero souborů (určitě ABA001 a BOA001), které na ftp už nejsou a lze těžko zjistit, co tam bylo - mohly tam být i soubory od jiných knihoven.

Ne mohly, ale zcela určitě byly:-) - třeba několik HKA001 z 18. 12.

**Comment by helena-oks** [comment]
Vypadá to, že procházejí soubory, které se dostaly na ftp dnes. Je třeba najít a pustit všechny soubory, co na ftp přišly dříve a už tam nejsou!

**Comment by JanMeritus** [comment]
@helena-oks  opravuje sa to postupne. Dozajtra by to malo byt.

**Comment by helena-oks** [comment]
Vypadá to, že proběhly i importy souborů z předchozího období. Prosím všechny, kdo je tam posílali, o ověření, zda prošlo vše a v pořádku.

ALE: soubory z adresáře CBA001, které přišly včera ráno na ftp (cba001r/importmarcxml - posílají to v pondělí v noci), tam již nejsou a import neproběhl! Dříve také import těchto souborů neprobíhal, ale soubory na ftp zůstávaly (ručně jsem je stěhovala). Viz issue 665.

**Comment by JanMeritus** [comment]
@helena-oks prosim o nasledne potvrdenie za dalsich uzivatelov, ze mimo CBA001 je vsetko v poriadku,

Co sa tyka #665 s udajmi uz boli predtym problemy, ktore sa nikdy uplne nepodarilo vyriesit mimo rucne zasahy. Prosim teda este len o kratku rekapitulaciu. 1. Posledny funkcny stav vyzeral, ze data ste rucne importovali z ich zlozky ftp, alebo sa staral o to importer? 2. Bolo ich treba nejako este doupravit, kvoli tomu ze neboli kompatibilne s formatom reliefu?

**Comment by indrakm** [comment]
@JanMeritus  Za MZK (BOA001) potvrzuji funkčnost, prošly i staré importy z prosince.

**Comment by helena-oks** [comment]
Soubory CBA001 se "našly" a budou zpracované (řešíme s D.G.). A protože zatím žádná stížnost od jiných knihoven nepřišla, mám za to, že je vše zpracované. Nyní běží program normálně.
