### ISSUE TITLE
Transfer repozitaru RD do NLCR

### ISSUE THREAD

**Issue by JanMeritus** [incad/registrdigitalizace#702]
Dobry den, 

@vlahoda @MKortus 

chcel by som poprosit o transfer repozitaru do oficialniho repozitare projektu NK (https://github.com/NLCR), kvoli sprave projektov, uzivatelov, ich timov, issues a privilegii.

Pojde o nasledovne projekty, prip. dalsie suvisiace s projektom RD:

- [ ] registrdigitalizace.search

- [ ] registrdigitalizace.harvest

- [ ] registrdigitalizace.soapservices

-  [ ] registrdigitalizace.mvnrepo

- [ ] registrdigitalizace.soapclient

- [ ] registrdigitalizace

prosim tiez o uvedenie, ktore z nich su uz legacy

**Comment by helena-oks** [comment]
Počítá se předpokládám s tím, že k tomu budou mít přístup i lidé z MZK a z KNAV!

**Comment by JanMeritus** [comment]
@helena-oks samozrejme, ostane online jako doted. Vyjmenovani uzivatelia budu mat zvysene prava.

EDIT: kludne sa pozrite na https://github.com/NLCR

**Comment by JanMeritus** [comment]
na zaklade diskusie Tymu RD NK uzavieram
