### ISSUE TITLE
Založení nových uživatelů

### ISSUE THREAD

**Issue by nezbedova** [incad/registrdigitalizace#703]
Na koho se mám obrátit s požadavkem na založení nových uživatelů a jejich přidání do roletky "Pracovník / Firma "?

**Comment by helena-oks** [comment]
Zatím prosím posílejte požadavky touto cestou přes issues - dořešíme mailem.

**Comment by nezbedova** [comment]
Po propojení Registru digitalizace a ProArcu nebudeme nové uživatele zakládat.

**Comment by JanMeritus** [comment]
uzatvaram
