### ISSUE TITLE
Nefunkční RD - vnitřní část

### ISSUE THREAD

**Issue by nezbedova** [incad/registrdigitalizace#708]
Do vnitřní části registru digitalizace se nedá přihlásit. Nezobrazí se ani přihlašovací stránka.

**Comment by nezbedova** [comment]
Od včerejšího odpoledne se nedá přihlásit do vnitřní části registru. Nezobrazí se ani přihlašovací stránka.

**Comment by nezbedova** [comment]
Dnes kolem poledne jsme zjistili, že se nedá přihlásit do vnitřní části registru. Nezobrazí se ani přihlašovací stránka.
@helena-oks

**Comment by helena-oks** [comment]
Info o problému se k CGI nedostala včas a já ten den nebyla v práci. Bylo dohodnuto, že dostanete přístup do prostředí gitlabu NK, abyste problémy mohla hlásit tam - zprávy odtud by měly chodit více pracovníkům CGI.
