### ISSUE TITLE
práva na uzavření issues, které založil někdo z Accenture

### ISSUE THREAD

**Issue by helena-oks** [incad/registrdigitalizace#709]
@JanMeritus Abychom měli přehled, potřebovala bych, aby se uzavřely issues, které jsou převedené do interního gitlabu a nezadávali je z KNAV. Můžu uzavřít jen to, co jsem založila.

**Comment by helena-oks** [comment]
Prosím uzavřít následující issues:
598,686,692 (pokud se konfigurace SOLR opravdu zálohuje), 703 
a po provedení i toto issue.

**Comment by JanMeritus** [comment]
pridano, 692 ostava, zvysok uzatvaram
