### ISSUE TITLE
Založení nového uživatele 

### ISSUE THREAD

**Issue by nezbedova** [incad/registrdigitalizace#711]
Prosím o založení nového uživatele jménem hz2054. Práva a nastavení podle uživatele Boudova. Přihlašovací údaje prosím zaslat na nezbedova@knav.cz. Děkuji

**Comment by nezbedova** [comment]
Dále prosím o zařazení "jmena" uživatele do roletky mezi "Pracovník/Firma:"

**Comment by helena-oks** [comment]
Uživatele se mi nepodařilo založit (systém tvrdí, že už existuje, ale v tabulce není). Takže doufám, že uspěje kolega Grešlík, pokud nemá dovolenou. Uživatel se zprovozní až po víkendu po založení.

**Comment by nezbedova** [comment]
Děkuji. Potřebuji to od 1. 9. Uživatel je úplně nový. leda byste měli stejného.

**Comment by helena-oks** [comment]
Uživatel je založen, heslo je stejné, pak si ho změňte. Aktivní by vše mělo být po nedělním restartu, prosím pak o potvrzení.

**Comment by nezbedova** [comment]
Děkuji. Ještě prosím o jednoho uživatele se stejnými právy a nastavením. Dále prosím o zařazení "jmena" uživatele do roletky mezi "Pracovník/Firma:"

Je to zs1616

**Comment by helena-oks** [comment]
Přidala jsem zs1616, ale funkčnost ověříte až příští týden. Předpokládám, že hz2054 funguje včetně roletky.

**Comment by nezbedova** [comment]
hz2054 přihlášení funguje. V roletce ji nevidím.

**Comment by helena-oks** [comment]
zs1616 pro přihlášení též funguje. Do roletky se zatím přidat nepodařilo - issue na interním gitlabu čeká...

**Comment by helena-oks** [comment]
Obě nová jména jsou i v roletce, vyzkoušeno. Problém byl v tom, že roletka pro pracovníky nepoužívá tabulku, co je společná pro všechny roletky, ale sahá si do nějaké zastaralé tabulky, kde by to nikdo nehledal...
